// src/web/svelte/src/pages/Chats.svelte
<script lang="ts">
import Chat from "../components/Chat.svelte";
import GroupModal from "../components/GroupModal.svelte";
import MindPickerModal from "../components/MindPickerModal.svelte";
import {
  type Conversation,
  deleteConversationById,
  fetchAllConversations,
  fetchMinds,
  type Mind,
  type Participant,
} from "../lib/api";

let {
  conversationId: initialId,
  mindName: initialMind,
  username,
}: {
  conversationId?: string;
  mindName?: string;
  username: string;
} = $props();

type ConversationWithParticipants = Conversation & { participants: Participant[] };

let conversations = $state<ConversationWithParticipants[]>([]);
let activeId = $state<string | null>(initialId ?? null);
let showNewChat = $state(false);
let showGroupModal = $state(false);
let newChatMind = $state<string | null>(initialMind ?? null);
let minds = $state<Mind[]>([]);

let activeConv = $derived(conversations.find((c) => c.id === activeId));

function refresh() {
  fetchAllConversations()
    .then((c) => {
      conversations = c;
    })
    .catch((e) => console.error("Failed to fetch conversations:", e));
  fetchMinds()
    .then((m) => {
      minds = m;
    })
    .catch((e) => console.error("Failed to fetch minds:", e));
}

$effect(() => {
  refresh();
  const interval = setInterval(refresh, 5000);
  return () => clearInterval(interval);
});

// Sync prop → state when navigating via URL
$effect(() => {
  activeId = initialId ?? null;
});

// Sync active conversation → hash
$effect(() => {
  if (activeId) {
    const expected = `#/chats/${activeId}`;
    if (window.location.hash !== expected) {
      window.history.replaceState(null, "", expected);
    }
  } else {
    const hash = window.location.hash.slice(1) || "/";
    if (hash.startsWith("/chats/")) {
      window.history.replaceState(null, "", "#/chats");
    }
  }
});

// Clear newChatMind once conversation list catches up
$effect(() => {
  if (activeId && activeConv) newChatMind = null;
});

function handleSelect(conv: ConversationWithParticipants) {
  activeId = conv.id;
}

function handleNew() {
  activeId = null;
  window.history.replaceState(null, "", "#/chats");
}

async function handleDelete(e: Event, id: string) {
  e.stopPropagation();
  try {
    await deleteConversationById(id);
  } catch (err) {
    console.error("Failed to delete conversation:", err);
    return;
  }
  refresh();
  if (activeId === id) handleNew();
}

function handleConversationId(id: string) {
  activeId = id;
  refresh();
}

function handleNewChatCreated(mind: string) {
  showNewChat = false;
  activeId = null;
  newChatMind = mind;
}

function handleGroupCreated(conv: Conversation) {
  showGroupModal = false;
  refresh();
  activeId = conv.id;
}

function getConversationLabel(conv: ConversationWithParticipants): string {
  const participants = conv.participants ?? [];
  if (participants.length === 2) {
    const other = participants.find((p) => p.username !== username);
    if (other) return `@${other.username}`;
  }
  if (conv.title) return conv.title;
  const mindParticipants = participants.filter((p) => p.userType === "mind");
  if (mindParticipants.length > 0) return mindParticipants.map((a) => a.username).join(", ");
  return "Untitled";
}

function getParticipantBadges(conv: ConversationWithParticipants): Participant[] {
  return conv.participants?.filter((p) => p.userType === "mind") ?? [];
}

let chatMindName = $derived(newChatMind || activeConv?.mind_name || "");
let chatMind = $derived(minds.find((m) => m.name === chatMindName));
</script>

<div class="chats">
  <!-- Sidebar -->
  <div class="sidebar">
    <div class="sidebar-actions">
      <button class="new-chat-btn" onclick={() => (showNewChat = true)}>+ new chat</button>
      <button class="group-btn" onclick={() => (showGroupModal = true)} title="New group">++</button>
    </div>
    <div class="conv-list">
      {#each conversations as conv (conv.id)}
        {@const badges = getParticipantBadges(conv)}
        {@const isSeed = minds.find((m) => m.name === conv.mind_name)?.stage === "seed"}
        <!-- svelte-ignore a11y_no_static_element_interactions -->
        <div
          class="conv-item"
          class:active={conv.id === activeId}
          onclick={() => handleSelect(conv)}
          onkeydown={() => {}}
        >
          <div class="conv-item-header">
            <div class="conv-item-label" class:active={conv.id === activeId}>
              <span class="conv-label-text">{getConversationLabel(conv)}</span>
              {#if isSeed}
                <span class="seed-tag">seed</span>
              {/if}
            </div>
            <button
              class="delete-btn"
              class:visible={conv.id === activeId}
              onclick={(e) => handleDelete(e, conv.id)}
            >
              x
            </button>
          </div>
          {#if badges.length > 0}
            <div class="badge-row">
              {#each badges as p}
                <span class="mind-badge">{p.username}</span>
              {/each}
            </div>
          {/if}
        </div>
      {/each}
      {#if conversations.length === 0}
        <div class="empty">No conversations yet</div>
      {/if}
    </div>
  </div>

  <!-- Chat panel -->
  <div class="chat-panel">
    {#if chatMindName}
      <Chat
        name={chatMindName}
        {username}
        conversationId={activeId}
        onConversationId={handleConversationId}
        stage={chatMind?.stage}
      />
    {:else}
      <div class="no-chat">Select a conversation or start a new chat</div>
    {/if}
  </div>

  {#if showNewChat}
    <MindPickerModal onClose={() => (showNewChat = false)} onPick={handleNewChatCreated} />
  {/if}
  {#if showGroupModal}
    <GroupModal onClose={() => (showGroupModal = false)} onCreated={handleGroupCreated} />
  {/if}
</div>

<style>
  .chats {
    display: flex;
    height: 100%;
    animation: fadeIn 0.2s ease both;
  }

  .sidebar {
    display: flex;
    flex-direction: column;
    width: 240px;
    flex-shrink: 0;
    border-right: 1px solid var(--border);
  }

  .sidebar-actions {
    display: flex;
    gap: 4px;
    padding: 8px;
  }

  .new-chat-btn {
    flex: 1;
    padding: 8px 12px;
    background: var(--accent-dim);
    color: var(--accent);
    border-radius: var(--radius);
    font-size: 12px;
    font-weight: 500;
    text-align: left;
  }

  .group-btn {
    padding: 8px 10px;
    background: var(--bg-2);
    color: var(--text-1);
    border-radius: var(--radius);
    font-size: 12px;
    border: 1px solid var(--border);
  }

  .conv-list {
    flex: 1;
    overflow: auto;
  }

  .conv-item {
    padding: 8px 12px;
    margin: 0 4px;
    cursor: pointer;
    border-radius: var(--radius);
    background: transparent;
    display: flex;
    flex-direction: column;
    gap: 2px;
    transition: background 0.1s;
  }

  .conv-item:hover {
    background: var(--bg-2);
  }

  .conv-item.active {
    background: var(--bg-3);
  }

  .conv-item-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 4px;
  }

  .conv-item-label {
    flex: 1;
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-size: 12px;
    color: var(--text-1);
    display: flex;
    align-items: center;
    gap: 6px;
  }

  .conv-item-label.active {
    color: var(--text-0);
  }

  .conv-label-text {
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .seed-tag {
    font-size: 9px;
    color: var(--yellow);
    flex-shrink: 0;
  }

  .delete-btn {
    background: transparent;
    color: var(--text-2);
    font-size: 11px;
    padding: 0 4px;
    flex-shrink: 0;
    visibility: hidden;
  }

  .delete-btn.visible {
    visibility: visible;
  }

  .badge-row {
    display: flex;
    gap: 4px;
    flex-wrap: wrap;
  }

  .mind-badge {
    font-size: 10px;
    color: var(--accent);
    background: var(--accent-bg);
    padding: 1px 5px;
    border-radius: 3px;
  }

  .empty {
    color: var(--text-2);
    font-size: 12px;
    padding: 16px 12px;
    text-align: center;
  }

  .chat-panel {
    flex: 1;
    padding-left: 16px;
    min-width: 0;
  }

  .no-chat {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100%;
    color: var(--text-2);
    font-size: 13px;
  }
</style>

// src/web/frontend/src/pages/Chats.tsx
import { useCallback, useEffect, useState } from "react";
import { Chat } from "../components/Chat";
import {
  type AvailableUser,
  type Conversation,
  createConversationWithParticipants,
  deleteConversationById,
  fetchAllConversations,
  fetchAvailableUsers,
  fetchMinds,
  type Mind,
  type Participant,
} from "../lib/api";

type ConversationWithParticipants = Conversation & { participants: Participant[] };

export function Chats({
  conversationId: initialId,
  mindName: initialMind,
  username,
}: {
  conversationId?: string;
  mindName?: string;
  username: string;
}) {
  const [conversations, setConversations] = useState<ConversationWithParticipants[]>([]);
  const [activeId, setActiveId] = useState<string | null>(initialId ?? null);
  const [showNewChat, setShowNewChat] = useState(false);
  const [showGroupModal, setShowGroupModal] = useState(false);
  const [newChatMind, setNewChatMind] = useState<string | null>(initialMind ?? null);
  const [minds, setMinds] = useState<Mind[]>([]);

  const activeConv = conversations.find((c) => c.id === activeId);
  const mindName = activeConv?.mind_name ?? "";

  const refresh = useCallback(() => {
    fetchAllConversations()
      .then(setConversations)
      .catch((e) => console.error("Failed to fetch conversations:", e));
    fetchMinds()
      .then(setMinds)
      .catch((e) => console.error("Failed to fetch minds:", e));
  }, []);

  useEffect(() => {
    refresh();
    const interval = setInterval(refresh, 5000);
    return () => clearInterval(interval);
  }, [refresh]);

  // Sync prop → state when navigating via URL
  useEffect(() => {
    setActiveId(initialId ?? null);
  }, [initialId]);

  // Sync active conversation → hash (only for internal selections, not external navigation)
  useEffect(() => {
    if (activeId) {
      const expected = `#/chats/${activeId}`;
      if (window.location.hash !== expected) {
        window.history.replaceState(null, "", expected);
      }
    } else {
      // When no active conversation, keep hash at chats root
      const hash = window.location.hash.slice(1) || "/";
      if (hash.startsWith("/chats/")) {
        window.history.replaceState(null, "", "#/chats");
      }
    }
  }, [activeId]);

  const handleSelect = (conv: ConversationWithParticipants) => {
    setActiveId(conv.id);
  };

  const handleNew = () => {
    setActiveId(null);
    window.history.replaceState(null, "", "#/chats");
  };

  const handleDelete = async (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    try {
      await deleteConversationById(id);
    } catch (err) {
      console.error("Failed to delete conversation:", err);
      return;
    }
    refresh();
    if (activeId === id) handleNew();
  };

  const handleConversationId = (id: string) => {
    setActiveId(id);
    refresh();
  };

  const handleNewChatCreated = (mind: string) => {
    setShowNewChat(false);
    setActiveId(null);
    setNewChatMind(mind);
  };

  // Clear newChatMind only once the conversation list has caught up
  useEffect(() => {
    if (activeId && activeConv) setNewChatMind(null);
  }, [activeId, activeConv]);

  const handleGroupCreated = (conv: Conversation) => {
    setShowGroupModal(false);
    refresh();
    setActiveId(conv.id);
  };

  // The mind name to use for the Chat component: from active conversation or new chat pick
  const chatMindName = newChatMind || mindName;
  const chatMind = minds.find((a) => a.name === chatMindName);

  function getConversationLabel(conv: ConversationWithParticipants): string {
    const participants = conv.participants ?? [];
    // DMs: show @otherUsername
    if (participants.length === 2) {
      const other = participants.find((p) => p.username !== username);
      if (other) return `@${other.username}`;
    }
    if (conv.title) return conv.title;
    const mindParticipants = participants.filter((p) => p.userType === "mind");
    if (mindParticipants.length > 0) return mindParticipants.map((a) => a.username).join(", ");
    return "Untitled";
  }

  function getParticipantBadges(conv: ConversationWithParticipants): Participant[] {
    return conv.participants?.filter((p) => p.userType === "mind") ?? [];
  }

  return (
    <div
      style={{
        display: "flex",
        height: "100%",
        animation: "fadeIn 0.2s ease both",
      }}
    >
      {/* Sidebar */}
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          width: 240,
          flexShrink: 0,
          borderRight: "1px solid var(--border)",
        }}
      >
        <div style={{ display: "flex", gap: 4, padding: "8px 8px 8px" }}>
          <button
            onClick={() => setShowNewChat(true)}
            style={{
              flex: 1,
              padding: "8px 12px",
              background: "var(--accent-dim)",
              color: "var(--accent)",
              borderRadius: "var(--radius)",
              fontSize: 12,
              fontWeight: 500,
              textAlign: "left" as const,
            }}
          >
            + new chat
          </button>
          <button
            onClick={() => setShowGroupModal(true)}
            style={{
              padding: "8px 10px",
              background: "var(--bg-2)",
              color: "var(--text-1)",
              borderRadius: "var(--radius)",
              fontSize: 12,
              border: "1px solid var(--border)",
            }}
            title="New group"
          >
            ++
          </button>
        </div>
        <div style={{ flex: 1, overflow: "auto" }}>
          {conversations.map((conv) => {
            const badges = getParticipantBadges(conv);
            return (
              <div
                key={conv.id}
                onClick={() => handleSelect(conv)}
                style={{
                  padding: "8px 12px",
                  margin: "0 4px",
                  cursor: "pointer",
                  borderRadius: "var(--radius)",
                  background: conv.id === activeId ? "var(--bg-3)" : "transparent",
                  display: "flex",
                  flexDirection: "column",
                  gap: 2,
                  transition: "background 0.1s",
                }}
                onMouseEnter={(e) => {
                  if (conv.id !== activeId) e.currentTarget.style.background = "var(--bg-2)";
                }}
                onMouseLeave={(e) => {
                  if (conv.id !== activeId) e.currentTarget.style.background = "transparent";
                }}
              >
                <div
                  style={{
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "space-between",
                    gap: 4,
                  }}
                >
                  <div
                    style={{
                      flex: 1,
                      minWidth: 0,
                      overflow: "hidden",
                      textOverflow: "ellipsis",
                      whiteSpace: "nowrap",
                      fontSize: 12,
                      color: conv.id === activeId ? "var(--text-0)" : "var(--text-1)",
                      display: "flex",
                      alignItems: "center",
                      gap: 6,
                    }}
                  >
                    <span style={{ overflow: "hidden", textOverflow: "ellipsis" }}>
                      {getConversationLabel(conv)}
                    </span>
                    {minds.find((a) => a.name === conv.mind_name)?.stage === "seed" && (
                      <span
                        style={{
                          fontSize: 9,
                          color: "var(--yellow)",
                          flexShrink: 0,
                        }}
                      >
                        seed
                      </span>
                    )}
                  </div>
                  <button
                    onClick={(e) => handleDelete(e, conv.id)}
                    style={{
                      background: "transparent",
                      color: "var(--text-2)",
                      fontSize: 11,
                      padding: "0 4px",
                      flexShrink: 0,
                      visibility: conv.id === activeId ? "visible" : "hidden",
                    }}
                  >
                    x
                  </button>
                </div>
                {badges.length > 0 && (
                  <div style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
                    {badges.map((p) => (
                      <span
                        key={p.userId}
                        style={{
                          fontSize: 10,
                          color: "var(--accent)",
                          background: "var(--accent-bg)",
                          padding: "1px 5px",
                          borderRadius: 3,
                        }}
                      >
                        {p.username}
                      </span>
                    ))}
                  </div>
                )}
              </div>
            );
          })}
          {conversations.length === 0 && (
            <div
              style={{
                color: "var(--text-2)",
                fontSize: 12,
                padding: "16px 12px",
                textAlign: "center",
              }}
            >
              No conversations yet
            </div>
          )}
        </div>
      </div>

      {/* Chat panel */}
      <div style={{ flex: 1, paddingLeft: 16, minWidth: 0 }}>
        {chatMindName ? (
          <Chat
            name={chatMindName}
            username={username}
            conversationId={activeId}
            onConversationId={handleConversationId}
            stage={chatMind?.stage}
          />
        ) : (
          <div
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              height: "100%",
              color: "var(--text-2)",
              fontSize: 13,
            }}
          >
            Select a conversation or start a new chat
          </div>
        )}
      </div>

      {showNewChat && (
        <MindPickerModal onClose={() => setShowNewChat(false)} onPick={handleNewChatCreated} />
      )}
      {showGroupModal && (
        <GroupModal onClose={() => setShowGroupModal(false)} onCreated={handleGroupCreated} />
      )}
    </div>
  );
}

function MindPickerModal({
  onClose,
  onPick,
}: {
  onClose: () => void;
  onPick: (mindName: string) => void;
}) {
  const [minds, setMinds] = useState<Mind[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    fetchMinds()
      .then((a) => {
        setMinds(a);
        setLoading(false);
      })
      .catch((e) => {
        console.error("Failed to fetch minds:", e);
        setLoading(false);
        setError("Failed to load minds");
      });
  }, []);

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        background: "rgba(0,0,0,0.5)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 100,
      }}
      onClick={onClose}
    >
      <div
        style={{
          background: "var(--bg-1)",
          border: "1px solid var(--border)",
          borderRadius: "var(--radius-lg)",
          padding: 20,
          width: 280,
          maxHeight: "50vh",
          display: "flex",
          flexDirection: "column",
          gap: 12,
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <div style={{ fontWeight: 600, color: "var(--text-0)", fontSize: 14 }}>
          New chat with...
        </div>
        {loading ? (
          <div style={{ color: "var(--text-2)", fontSize: 12 }}>Loading minds...</div>
        ) : error ? (
          <div style={{ color: "var(--red)", fontSize: 12, padding: 8 }}>{error}</div>
        ) : (
          <div style={{ flex: 1, overflow: "auto" }}>
            {minds.map((a) => (
              <button
                key={a.name}
                onClick={() => onPick(a.name)}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 8,
                  width: "100%",
                  padding: "8px 10px",
                  background: "transparent",
                  color: "var(--text-0)",
                  fontSize: 13,
                  borderRadius: "var(--radius)",
                  textAlign: "left",
                  transition: "background 0.1s",
                }}
                onMouseEnter={(e) => (e.currentTarget.style.background = "var(--bg-2)")}
                onMouseLeave={(e) => (e.currentTarget.style.background = "transparent")}
              >
                <span
                  style={{
                    width: 8,
                    height: 8,
                    borderRadius: "50%",
                    background: a.status === "running" ? "var(--accent)" : "var(--text-2)",
                    flexShrink: 0,
                  }}
                />
                {a.name}
              </button>
            ))}
            {minds.length === 0 && (
              <div style={{ color: "var(--text-2)", fontSize: 12, padding: 8 }}>No minds found</div>
            )}
          </div>
        )}
        <button
          onClick={onClose}
          style={{
            padding: "6px 14px",
            background: "var(--bg-2)",
            color: "var(--text-1)",
            borderRadius: "var(--radius)",
            fontSize: 12,
            border: "1px solid var(--border)",
            alignSelf: "flex-end",
          }}
        >
          Cancel
        </button>
      </div>
    </div>
  );
}

function GroupModal({
  onClose,
  onCreated,
}: {
  onClose: () => void;
  onCreated: (conv: Conversation) => void;
}) {
  const [users, setUsers] = useState<AvailableUser[]>([]);
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [title, setTitle] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    fetchAvailableUsers()
      .then(setUsers)
      .catch(() => setError("Failed to load users"));
  }, []);

  const toggle = (username: string) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(username)) next.delete(username);
      else next.add(username);
      return next;
    });
  };

  const hasMind = users.some((u) => u.user_type === "mind" && selected.has(u.username));

  const handleCreate = async () => {
    if (!hasMind) {
      setError("Select at least one mind");
      return;
    }
    setLoading(true);
    setError("");
    try {
      const conv = await createConversationWithParticipants([...selected], title || undefined);
      onCreated(conv);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to create");
      setLoading(false);
    }
  };

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        background: "rgba(0,0,0,0.5)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 100,
      }}
      onClick={onClose}
    >
      <div
        style={{
          background: "var(--bg-1)",
          border: "1px solid var(--border)",
          borderRadius: "var(--radius-lg)",
          padding: 20,
          width: 340,
          maxHeight: "70vh",
          display: "flex",
          flexDirection: "column",
          gap: 12,
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <div style={{ fontWeight: 600, color: "var(--text-0)", fontSize: 14 }}>
          New group conversation
        </div>

        <input
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          placeholder="Title (optional)"
          style={{
            background: "var(--bg-2)",
            border: "1px solid var(--border)",
            borderRadius: "var(--radius)",
            padding: "8px 10px",
            color: "var(--text-0)",
            fontSize: 12,
            outline: "none",
            fontFamily: "var(--mono)",
          }}
        />

        <div style={{ color: "var(--text-2)", fontSize: 11 }}>
          Select participants (at least one mind):
        </div>
        <div style={{ flex: 1, overflow: "auto", maxHeight: 250 }}>
          {users.map((u) => (
            <label
              key={u.id}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 8,
                padding: "6px 4px",
                cursor: "pointer",
                fontSize: 12,
                color: "var(--text-0)",
              }}
            >
              <input
                type="checkbox"
                checked={selected.has(u.username)}
                onChange={() => toggle(u.username)}
              />
              <span>{u.username}</span>
              <span
                style={{
                  color: u.user_type === "mind" ? "var(--accent)" : "var(--text-2)",
                  fontSize: 10,
                  marginLeft: "auto",
                }}
              >
                {u.user_type}
              </span>
            </label>
          ))}
        </div>

        {error && <div style={{ color: "var(--red)", fontSize: 11 }}>{error}</div>}

        <div style={{ display: "flex", gap: 8, justifyContent: "flex-end" }}>
          <button
            onClick={onClose}
            style={{
              padding: "6px 14px",
              background: "var(--bg-2)",
              color: "var(--text-1)",
              borderRadius: "var(--radius)",
              fontSize: 12,
              border: "1px solid var(--border)",
            }}
          >
            Cancel
          </button>
          <button
            onClick={handleCreate}
            disabled={loading || !hasMind}
            style={{
              padding: "6px 14px",
              background: "var(--accent-dim)",
              color: "var(--accent)",
              borderRadius: "var(--radius)",
              fontSize: 12,
              fontWeight: 500,
              opacity: loading || !hasMind ? 0.5 : 1,
            }}
          >
            {loading ? "Creating..." : "Create"}
          </button>
        </div>
      </div>
    </div>
  );
}
