// src/web/ui/src/pages/Dashboard.svelte
<script lang="ts">
import MindCard from "../components/MindCard.svelte";
import SeedModal from "../components/SeedModal.svelte";
import { fetchMinds, type Mind } from "../lib/api";
import { navigate } from "../lib/navigate";

let minds = $state<Mind[]>([]);
let error = $state("");
let loading = $state(true);
let showSeedModal = $state(false);

$effect(() => {
  let active = true;
  const poll = async () => {
    try {
      const data = await fetchMinds();
      if (active) {
        minds = data;
        error = "";
        loading = false;
      }
    } catch {
      if (active) {
        error = "Failed to connect to API";
        loading = false;
      }
    }
  };

  poll();
  const interval = setInterval(poll, 5000);
  return () => {
    active = false;
    clearInterval(interval);
  };
});

function handleSeedCreated(mindName: string) {
  showSeedModal = false;
  navigate(`/chats?mind=${mindName}`);
}
</script>

{#if error}
  <div class="error">{error}</div>
{:else if loading}
  <!-- loading -->
{:else if minds.length === 0}
  <div class="empty">
    <div class="empty-text">No minds registered.</div>
    <div class="empty-actions">
      <code class="code-hint">volute mind create &lt;name&gt;</code>
      <span class="or">or</span>
      <button class="seed-btn" onclick={() => showSeedModal = true}>plant a seed</button>
    </div>
  </div>
{:else}
  <div class="toolbar">
    <button class="seed-btn" onclick={() => showSeedModal = true}>plant a seed</button>
  </div>
  <div class="grid">
    {#each minds as mind, i}
      <div class="card-wrapper" style:animation-delay={`${i * 50}ms`}>
        <MindCard {mind} />
      </div>
    {/each}
  </div>
{/if}

{#if showSeedModal}
  <SeedModal onClose={() => showSeedModal = false} onCreated={handleSeedCreated} />
{/if}

<style>
  .error {
    color: var(--red);
    padding: 40px;
    text-align: center;
  }

  .empty {
    color: var(--text-2);
    padding: 40px;
    text-align: center;
    font-size: 14px;
  }

  .empty-text {
    margin-bottom: 8px;
  }

  .empty-actions {
    display: flex;
    gap: 12px;
    justify-content: center;
    margin-top: 16px;
  }

  .code-hint {
    color: var(--text-1);
  }

  .or {
    color: var(--text-2);
  }

  .seed-btn {
    padding: 6px 14px;
    background: rgba(251, 191, 36, 0.08);
    color: var(--yellow);
    border-radius: var(--radius);
    font-size: 12px;
    font-weight: 500;
    border: 1px solid rgba(251, 191, 36, 0.2);
    cursor: pointer;
  }

  .toolbar {
    margin-bottom: 16px;
  }

  .grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 16px;
    max-width: 1200px;
  }

  .card-wrapper {
    animation: fadeIn 0.3s ease both;
  }
</style>

// src/web/frontend/src/pages/Dashboard.tsx
import { useEffect, useState } from "react";
import { MindCard } from "../components/MindCard";
import { SeedModal } from "../components/SeedModal";
import { fetchMinds, type Mind } from "../lib/api";

export function Dashboard() {
  const [minds, setMinds] = useState<Mind[]>([]);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [showSeedModal, setShowSeedModal] = useState(false);

  useEffect(() => {
    let active = true;
    const poll = async () => {
      try {
        const data = await fetchMinds();
        if (active) {
          setMinds(data);
          setError("");
          setLoading(false);
        }
      } catch {
        if (active) {
          setError("Failed to connect to API");
          setLoading(false);
        }
      }
    };

    poll();
    const interval = setInterval(poll, 5000);
    return () => {
      active = false;
      clearInterval(interval);
    };
  }, []);

  const handleSeedCreated = (mindName: string) => {
    setShowSeedModal(false);
    window.location.hash = `#/chats?mind=${mindName}`;
  };

  if (error) {
    return <div style={{ color: "var(--red)", padding: 40, textAlign: "center" }}>{error}</div>;
  }

  if (loading) {
    return null;
  }

  if (minds.length === 0) {
    return (
      <div
        style={{
          color: "var(--text-2)",
          padding: 40,
          textAlign: "center",
          fontSize: 14,
        }}
      >
        <div style={{ marginBottom: 8 }}>No minds registered.</div>
        <div style={{ display: "flex", gap: 12, justifyContent: "center", marginTop: 16 }}>
          <code style={{ color: "var(--text-1)" }}>volute mind create &lt;name&gt;</code>
          <span style={{ color: "var(--text-2)" }}>or</span>
          <button
            onClick={() => setShowSeedModal(true)}
            style={{
              padding: "4px 12px",
              background: "rgba(251, 191, 36, 0.08)",
              color: "var(--yellow)",
              borderRadius: "var(--radius)",
              fontSize: 12,
              fontWeight: 500,
              border: "1px solid rgba(251, 191, 36, 0.2)",
              cursor: "pointer",
            }}
          >
            plant a seed
          </button>
        </div>
        {showSeedModal && (
          <SeedModal onClose={() => setShowSeedModal(false)} onCreated={handleSeedCreated} />
        )}
      </div>
    );
  }

  return (
    <>
      <div style={{ marginBottom: 16 }}>
        <button
          onClick={() => setShowSeedModal(true)}
          style={{
            padding: "6px 14px",
            background: "rgba(251, 191, 36, 0.08)",
            color: "var(--yellow)",
            borderRadius: "var(--radius)",
            fontSize: 12,
            fontWeight: 500,
            border: "1px solid rgba(251, 191, 36, 0.2)",
            cursor: "pointer",
          }}
        >
          plant a seed
        </button>
      </div>
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
          gap: 16,
          maxWidth: 1200,
        }}
      >
        {minds.map((mind, i) => (
          <div
            key={mind.name}
            style={{
              animation: "fadeIn 0.3s ease both",
              animationDelay: `${i * 50}ms`,
            }}
          >
            <MindCard mind={mind} />
          </div>
        ))}
      </div>
      {showSeedModal && (
        <SeedModal onClose={() => setShowSeedModal(false)} onCreated={handleSeedCreated} />
      )}
    </>
  );
}
