// src/web/ui/src/pages/Home.svelte
<script lang="ts">
import StatusBadge from "../components/StatusBadge.svelte";
import {
  type Conversation,
  fetchAllConversations,
  fetchMinds,
  fetchRecentPages,
  type LastMessageSummary,
  type Mind,
  type Participant,
  type RecentPage,
} from "../lib/api";
import { formatRelativeTime, getConversationLabel } from "../lib/format";

let { username }: { username: string } = $props();

type ConversationWithDetails = Conversation & {
  participants: Participant[];
  lastMessage?: LastMessageSummary;
};

let minds = $state<Mind[]>([]);
let conversations = $state<ConversationWithDetails[]>([]);
let recentPages = $state<RecentPage[]>([]);
let error = $state("");

$effect(() => {
  fetchMinds()
    .then((m) => {
      minds = m;
    })
    .catch(() => {
      error = "Failed to load data";
    });
  fetchAllConversations()
    .then((c) => {
      conversations = c;
    })
    .catch(() => {
      error = "Failed to load data";
    });
  fetchRecentPages()
    .then((p) => {
      recentPages = p;
    })
    .catch(() => {
      error = "Failed to load data";
    });
});

let sortedMinds = $derived(
  [...minds].sort((a, b) => {
    if (a.status === "running" && b.status !== "running") return -1;
    if (a.status !== "running" && b.status === "running") return 1;
    const aTime = a.lastActiveAt ?? "";
    const bTime = b.lastActiveAt ?? "";
    return bTime.localeCompare(aTime);
  }),
);

let recentConversations = $derived(
  [...conversations]
    .sort((a, b) => {
      const normalize = (d: string) => (d.endsWith("Z") ? d : `${d}Z`);
      return (
        new Date(normalize(b.updated_at)).getTime() - new Date(normalize(a.updated_at)).getTime()
      );
    })
    .slice(0, 5),
);

function getDisplayStatus(mind: Mind): string {
  if (mind.status !== "running") return mind.status;
  if (!mind.lastActiveAt) return "running";
  const ago = Date.now() - new Date(`${mind.lastActiveAt}Z`).getTime();
  return ago < 5 * 60_000 ? "active" : "running";
}
</script>

<div class="home">
  {#if error}
    <div class="error">{error}</div>
  {/if}
  <!-- Minds -->
  <div class="section">
    <div class="section-header">
      <span class="section-title">minds</span>
      <a href="/minds" class="section-link">all minds &rarr;</a>
    </div>
    {#if minds.length === 0}
      <div class="empty-hint">
        No minds registered. Run <code class="code-hint">volute mind create &lt;name&gt;</code> to get started.
      </div>
    {:else}
      <div class="mind-row">
        {#each sortedMinds as mind}
          {@const connectedChannels = mind.channels.filter(ch => ch.name !== "web" && ch.name !== "volute" && ch.status === "connected")}
          <a href={`/mind/${mind.name}`} class="home-mind-card">
            <div class="mind-card-header">
              <span class="mind-name">{mind.name}</span>
              <StatusBadge status={getDisplayStatus(mind)} />
              {#if mind.stage === "seed"}
                <span class="seed-tag">seed</span>
              {/if}
            </div>
            {#if connectedChannels.length > 0}
              <div class="channel-row">
                {#each connectedChannels as ch}
                  <span class="channel-chip">{ch.displayName || ch.name}</span>
                {/each}
              </div>
            {/if}
            <div class="mind-activity">
              {mind.lastActiveAt ? `active ${formatRelativeTime(mind.lastActiveAt)}` : "no activity"}
            </div>
          </a>
        {/each}
      </div>
    {/if}
  </div>

  <!-- Recent conversations -->
  {#if recentConversations.length > 0}
    <div class="section">
      <div class="section-header">
        <span class="section-title">recent conversations</span>
        <a href="/chats" class="section-link">open chat &rarr;</a>
      </div>
      <div class="conv-list">
        {#each recentConversations as conv}
          {@const label = getConversationLabel(conv.participants ?? [], conv.title, username)}
          {@const isSeed = minds.find(a => a.name === conv.mind_name)?.stage === "seed"}
          {@const msg = conv.lastMessage}
          <a href={`/chats/${conv.id}`} class="conv-card">
            <div class="conv-content">
              <div class="conv-header">
                <span class="conv-label">{label}</span>
                {#if isSeed}
                  <span class="seed-tag">seed</span>
                {/if}
              </div>
              {#if msg}
                <div class="conv-preview">
                  {msg.senderName ? `${msg.senderName}: ` : ""}{msg.text}
                </div>
              {/if}
            </div>
            <span class="conv-time">{formatRelativeTime(conv.updated_at)}</span>
          </a>
        {/each}
      </div>
    </div>
  {/if}

  <!-- Recent pages -->
  {#if recentPages.length > 0}
    <div class="section">
      <div class="section-header">
        <span class="section-title">recent pages</span>
      </div>
      <div class="pages-list">
        {#each recentPages as page}
          <a href={page.url} target="_blank" rel="noopener noreferrer" class="page-row">
            <span>
              <span class="page-mind">{page.mind}/</span>{page.file}
            </span>
            <span class="page-time">{formatRelativeTime(page.modified)}</span>
          </a>
        {/each}
      </div>
    </div>
  {/if}
</div>

<style>
  .error {
    color: var(--red);
    font-size: 12px;
    margin-bottom: 16px;
  }

  .home {
    max-width: 800px;
    animation: fadeIn 0.2s ease both;
  }

  .section {
    margin-bottom: 24px;
  }

  .section-header {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    margin-bottom: 8px;
  }

  .section-title {
    color: var(--text-2);
  }

  .section-link {
    color: var(--text-2);
    font-size: 10px;
    text-transform: none;
  }

  .section-link:hover {
    color: var(--text-1);
  }

  .empty-hint {
    color: var(--text-2);
    font-size: 12px;
  }

  .code-hint {
    color: var(--text-1);
  }

  .mind-row {
    display: flex;
    gap: 10px;
    overflow-x: auto;
    padding-bottom: 4px;
  }

  .home-mind-card {
    display: flex;
    flex-direction: column;
    gap: 6px;
    padding: 10px 14px;
    border-radius: var(--radius-lg);
    background: var(--bg-2);
    border: 1px solid var(--border);
    min-width: 150px;
    transition: border-color 0.15s;
    flex-shrink: 0;
  }

  .home-mind-card:hover {
    border-color: var(--border-bright);
  }

  .mind-card-header {
    display: flex;
    align-items: center;
    gap: 6px;
  }

  .mind-name {
    color: var(--text-0);
    font-weight: 500;
    font-size: 13px;
  }

  .seed-tag {
    font-size: 9px;
    color: var(--yellow);
  }

  .channel-row {
    display: flex;
    gap: 4px;
    flex-wrap: wrap;
  }

  .channel-chip {
    font-size: 10px;
    padding: 1px 5px;
    border-radius: 3px;
    background: var(--accent-dim);
    color: var(--accent);
  }

  .mind-activity {
    font-size: 10px;
    color: var(--text-2);
  }

  .conv-list {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }

  .conv-card {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 10px 14px;
    border-radius: var(--radius-lg);
    background: var(--bg-2);
    border: 1px solid var(--border);
    transition: border-color 0.15s;
  }

  .conv-card:hover {
    border-color: var(--border-bright);
  }

  .conv-content {
    flex: 1;
    min-width: 0;
  }

  .conv-header {
    display: flex;
    align-items: center;
    gap: 6px;
    margin-bottom: 2px;
  }

  .conv-label {
    color: var(--text-0);
    font-weight: 500;
    font-size: 12px;
  }

  .conv-preview {
    font-size: 11px;
    color: var(--text-2);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .conv-time {
    color: var(--text-2);
    font-size: 10px;
    flex-shrink: 0;
  }

  .pages-list {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }

  .page-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 8px 12px;
    border-radius: var(--radius);
    background: var(--bg-2);
    border: 1px solid var(--border);
    text-decoration: none;
    color: var(--text-0);
    font-size: 12px;
    transition: border-color 0.15s;
  }

  .page-row:hover {
    border-color: var(--border-bright);
  }

  .page-mind {
    color: var(--text-2);
  }

  .page-time {
    color: var(--text-2);
    font-size: 10px;
  }
</style>

// src/web/frontend/src/pages/Home.tsx
import { useEffect, useState } from "react";
import { StatusBadge } from "../components/StatusBadge";
import {
  type Conversation,
  fetchAllConversations,
  fetchMinds,
  fetchRecentPages,
  type LastMessageSummary,
  type Mind,
  type Participant,
  type RecentPage,
} from "../lib/api";

type ConversationWithDetails = Conversation & {
  participants: Participant[];
  lastMessage?: LastMessageSummary;
};

function getConversationLabel(conv: ConversationWithDetails, username: string): string {
  const participants = conv.participants ?? [];
  if (participants.length === 2) {
    const other = participants.find((p) => p.username !== username);
    if (other) return `@${other.username}`;
  }
  if (conv.title) return conv.title;
  const minds = participants.filter((p) => p.userType === "mind");
  if (minds.length > 0) return minds.map((a) => a.username).join(", ");
  return "Untitled";
}

export function Home({ username }: { username: string }) {
  const [minds, setMinds] = useState<Mind[]>([]);
  const [conversations, setConversations] = useState<ConversationWithDetails[]>([]);
  const [recentPages, setRecentPages] = useState<RecentPage[]>([]);

  useEffect(() => {
    fetchMinds()
      .then(setMinds)
      .catch(() => {});
    fetchAllConversations()
      .then(setConversations)
      .catch(() => {});
    fetchRecentPages()
      .then(setRecentPages)
      .catch(() => {});
  }, []);

  // Sort minds: running first, then by most recent activity
  const sortedMinds = [...minds].sort((a, b) => {
    if (a.status === "running" && b.status !== "running") return -1;
    if (a.status !== "running" && b.status === "running") return 1;
    const aTime = a.lastActiveAt ?? "";
    const bTime = b.lastActiveAt ?? "";
    return bTime.localeCompare(aTime);
  });

  const recentConversations = [...conversations]
    .sort((a, b) => {
      const normalize = (d: string) => (d.endsWith("Z") ? d : `${d}Z`);
      return (
        new Date(normalize(b.updated_at)).getTime() - new Date(normalize(a.updated_at)).getTime()
      );
    })
    .slice(0, 5);

  return (
    <div style={{ maxWidth: 800, animation: "fadeIn 0.2s ease both" }}>
      {/* Minds */}
      <Section title="minds" href="#/minds" linkLabel="all minds">
        {minds.length === 0 ? (
          <div style={{ color: "var(--text-2)", fontSize: 12 }}>
            No minds registered. Run{" "}
            <code style={{ color: "var(--text-1)" }}>volute mind create &lt;name&gt;</code> to get
            started.
          </div>
        ) : (
          <div style={{ display: "flex", gap: 10, overflowX: "auto", paddingBottom: 4 }}>
            {sortedMinds.map((a) => (
              <MindCard key={a.name} mind={a} />
            ))}
          </div>
        )}
      </Section>

      {/* Recent conversations */}
      {recentConversations.length > 0 && (
        <Section title="recent conversations" href="#/chats" linkLabel="open chat">
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {recentConversations.map((conv) => (
              <ConversationCard key={conv.id} conv={conv} username={username} minds={minds} />
            ))}
          </div>
        </Section>
      )}

      {/* Recent pages */}
      {recentPages.length > 0 && (
        <Section title="recent pages">
          <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
            {recentPages.map((page) => (
              <a
                key={`${page.mind}/${page.file}`}
                href={page.url}
                target="_blank"
                rel="noopener noreferrer"
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  padding: "8px 12px",
                  borderRadius: "var(--radius)",
                  background: "var(--bg-2)",
                  border: "1px solid var(--border)",
                  textDecoration: "none",
                  color: "var(--text-0)",
                  fontSize: 12,
                  transition: "border-color 0.15s",
                }}
                onMouseEnter={(e) => (e.currentTarget.style.borderColor = "var(--border-bright)")}
                onMouseLeave={(e) => (e.currentTarget.style.borderColor = "var(--border)")}
              >
                <span>
                  <span style={{ color: "var(--text-2)" }}>{page.mind}/</span>
                  {page.file}
                </span>
                <span style={{ color: "var(--text-2)", fontSize: 10 }}>
                  {formatRelativeTime(page.modified)}
                </span>
              </a>
            ))}
          </div>
        </Section>
      )}
    </div>
  );
}

function Section({
  title,
  href,
  linkLabel,
  children,
}: {
  title: string;
  href?: string;
  linkLabel?: string;
  children: React.ReactNode;
}) {
  return (
    <div style={{ marginBottom: 24 }}>
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 8,
          fontSize: 11,
          textTransform: "uppercase",
          letterSpacing: "0.05em",
          marginBottom: 8,
        }}
      >
        <span style={{ color: "var(--text-2)" }}>{title}</span>
        {href && linkLabel && (
          <a
            href={href}
            style={{ color: "var(--text-2)", fontSize: 10, textTransform: "none" }}
            onMouseEnter={(e) => (e.currentTarget.style.color = "var(--text-1)")}
            onMouseLeave={(e) => (e.currentTarget.style.color = "var(--text-2)")}
          >
            {linkLabel} &rarr;
          </a>
        )}
      </div>
      {children}
    </div>
  );
}

function getDisplayStatus(mind: Mind): string {
  if (mind.status !== "running") return mind.status;
  if (!mind.lastActiveAt) return "running";
  const ago = Date.now() - new Date(`${mind.lastActiveAt}Z`).getTime();
  return ago < 5 * 60_000 ? "active" : "running";
}

function MindCard({ mind }: { mind: Mind }) {
  const channels = mind.channels.filter(
    (ch) => ch.name !== "web" && ch.name !== "volute" && ch.status === "connected",
  );

  return (
    <a
      href={`#/mind/${mind.name}`}
      style={{
        display: "flex",
        flexDirection: "column",
        gap: 6,
        padding: "10px 14px",
        borderRadius: "var(--radius-lg)",
        background: "var(--bg-2)",
        border: "1px solid var(--border)",
        minWidth: 150,
        transition: "border-color 0.15s",
        flexShrink: 0,
      }}
      onMouseEnter={(e) => (e.currentTarget.style.borderColor = "var(--border-bright)")}
      onMouseLeave={(e) => (e.currentTarget.style.borderColor = "var(--border)")}
    >
      <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
        <span style={{ color: "var(--text-0)", fontWeight: 500, fontSize: 13 }}>{mind.name}</span>
        <StatusBadge status={getDisplayStatus(mind)} />
        {mind.stage === "seed" && <span style={{ fontSize: 9, color: "var(--yellow)" }}>seed</span>}
      </div>
      {channels.length > 0 && (
        <div style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
          {channels.map((ch) => (
            <span
              key={ch.name}
              style={{
                fontSize: 10,
                padding: "1px 5px",
                borderRadius: 3,
                background: "var(--accent-dim)",
                color: "var(--accent)",
              }}
            >
              {ch.displayName || ch.name}
            </span>
          ))}
        </div>
      )}
      <div style={{ fontSize: 10, color: "var(--text-2)" }}>
        {mind.lastActiveAt ? `active ${formatRelativeTime(mind.lastActiveAt)}` : "no activity"}
      </div>
    </a>
  );
}

function ConversationCard({
  conv,
  username,
  minds,
}: {
  conv: ConversationWithDetails;
  username: string;
  minds: Mind[];
}) {
  const label = getConversationLabel(conv, username);
  const isSeed = minds.find((a) => a.name === conv.mind_name)?.stage === "seed";
  const msg = conv.lastMessage;

  let preview = "";
  if (msg) {
    const sender = msg.senderName ? `${msg.senderName}: ` : "";
    preview = sender + msg.text;
  }

  return (
    <a
      href={`#/chats/${conv.id}`}
      style={{
        display: "flex",
        alignItems: "center",
        gap: 12,
        padding: "10px 14px",
        borderRadius: "var(--radius-lg)",
        background: "var(--bg-2)",
        border: "1px solid var(--border)",
        transition: "border-color 0.15s",
      }}
      onMouseEnter={(e) => (e.currentTarget.style.borderColor = "var(--border-bright)")}
      onMouseLeave={(e) => (e.currentTarget.style.borderColor = "var(--border)")}
    >
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 2 }}>
          <span style={{ color: "var(--text-0)", fontWeight: 500, fontSize: 12 }}>{label}</span>
          {isSeed && <span style={{ fontSize: 9, color: "var(--yellow)" }}>seed</span>}
        </div>
        {preview && (
          <div
            style={{
              fontSize: 11,
              color: "var(--text-2)",
              overflow: "hidden",
              textOverflow: "ellipsis",
              whiteSpace: "nowrap",
            }}
          >
            {preview}
          </div>
        )}
      </div>
      <span style={{ color: "var(--text-2)", fontSize: 10, flexShrink: 0 }}>
        {formatRelativeTime(conv.updated_at)}
      </span>
    </a>
  );
}

function formatRelativeTime(dateStr: string): string {
  const now = Date.now();
  // SQLite datetime('now') stores UTC without Z suffix; ensure UTC parsing
  const normalized = dateStr.endsWith("Z") ? dateStr : `${dateStr}Z`;
  const then = new Date(normalized).getTime();
  const diff = now - then;
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}
