// src/web/frontend/src/components/LoginPage.tsx
import { useState } from "react";
import { type AuthUser, login, register } from "../lib/auth";

export function LoginPage({ onAuth }: { onAuth: (user: AuthUser) => void }) {
  const [mode, setMode] = useState<"login" | "register">("login");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [pendingMessage, setPendingMessage] = useState("");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!username.trim() || !password.trim()) return;
    setError("");
    setLoading(true);

    try {
      if (mode === "login") {
        const user = await login(username, password);
        if (user.role === "pending") {
          setPendingMessage("Your account is pending approval by an admin.");
        } else {
          onAuth(user);
        }
      } else {
        const user = await register(username, password);
        if (user.role === "admin") {
          // First user, auto-logged in
          onAuth(user);
        } else {
          setPendingMessage("Account created. Waiting for admin approval.");
        }
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong");
    }
    setLoading(false);
  };

  if (pendingMessage) {
    return (
      <div style={containerStyle}>
        <div style={cardStyle}>
          <div style={{ color: "var(--yellow)", marginBottom: 16 }}>{pendingMessage}</div>
          <button
            onClick={() => {
              setPendingMessage("");
              setMode("login");
            }}
            style={linkBtnStyle}
          >
            Back to login
          </button>
        </div>
      </div>
    );
  }

  return (
    <div style={containerStyle}>
      <div style={cardStyle}>
        <div style={{ marginBottom: 24, textAlign: "center" as const }}>
          <div style={{ fontSize: 18, fontWeight: 600, marginBottom: 4 }}>
            <span style={{ color: "var(--accent)" }}>&gt;</span> volute
          </div>
          <div style={{ color: "var(--text-2)", fontSize: 12 }}>
            {mode === "login" ? "Sign in to continue" : "Create an account"}
          </div>
        </div>

        <form onSubmit={handleSubmit}>
          <input
            type="text"
            placeholder="username"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            style={inputStyle}
          />
          <input
            type="password"
            placeholder="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            style={{ ...inputStyle, marginTop: 8 }}
          />
          {error && <div style={{ color: "var(--red)", fontSize: 12, marginTop: 8 }}>{error}</div>}
          <button
            type="submit"
            disabled={loading || !username.trim() || !password.trim()}
            style={{
              ...btnStyle,
              marginTop: 16,
              opacity: loading ? 0.5 : 1,
            }}
          >
            {loading ? "..." : mode === "login" ? "Sign in" : "Create account"}
          </button>
        </form>

        <div style={{ marginTop: 16, textAlign: "center" as const }}>
          <button
            onClick={() => {
              setMode(mode === "login" ? "register" : "login");
              setError("");
            }}
            style={linkBtnStyle}
          >
            {mode === "login" ? "Need an account? Register" : "Have an account? Sign in"}
          </button>
        </div>
      </div>
    </div>
  );
}

const containerStyle: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  height: "100%",
  padding: 24,
};

const cardStyle: React.CSSProperties = {
  width: 320,
  padding: 32,
  background: "var(--bg-1)",
  border: "1px solid var(--border)",
  borderRadius: "var(--radius-lg)",
};

const inputStyle: React.CSSProperties = {
  width: "100%",
  padding: "10px 12px",
  background: "var(--bg-2)",
  border: "1px solid var(--border)",
  borderRadius: "var(--radius)",
  color: "var(--text-0)",
  fontFamily: "var(--mono)",
  fontSize: 13,
  outline: "none",
};

const btnStyle: React.CSSProperties = {
  width: "100%",
  padding: "10px 16px",
  background: "var(--accent-dim)",
  color: "var(--accent)",
  borderRadius: "var(--radius)",
  fontSize: 13,
  fontWeight: 500,
  fontFamily: "var(--mono)",
  border: "none",
  cursor: "pointer",
};

const linkBtnStyle: React.CSSProperties = {
  background: "transparent",
  color: "var(--text-2)",
  fontSize: 12,
  fontFamily: "var(--mono)",
  border: "none",
  cursor: "pointer",
  padding: 0,
};

// packages/web/src/ui/components/LoginPage.svelte
<script lang="ts">
import { Input } from "@volute/ui";
import { type AuthUser, login, register } from "../lib/auth";

let { onAuth }: { onAuth: (user: AuthUser) => void } = $props();

let mode = $state<"login" | "register">("login");
let username = $state("");
let password = $state("");
let error = $state("");
let loading = $state(false);
let pendingMessage = $state("");

async function handleSubmit(e: Event) {
  e.preventDefault();
  if (!username.trim() || !password.trim()) return;
  error = "";
  loading = true;

  try {
    if (mode === "login") {
      const user = await login(username, password);
      if (user.role === "pending") {
        pendingMessage = "Your account is pending approval by an admin.";
      } else {
        onAuth(user);
      }
    } else {
      const user = await register(username, password);
      if (user.role === "admin") {
        onAuth(user);
      } else {
        pendingMessage = "Account created. Waiting for admin approval.";
      }
    }
  } catch (err) {
    error = err instanceof Error ? err.message : "Something went wrong";
  }
  loading = false;
}
</script>

{#if pendingMessage}
  <div class="container">
    <div class="card">
      <div class="pending-msg">{pendingMessage}</div>
      <button class="link-btn" onclick={() => { pendingMessage = ""; mode = "login"; }}>
        Back to login
      </button>
    </div>
  </div>
{:else}
  <div class="container">
    <div class="card">
      <div class="branding">
        <div class="logo-row">
          <span class="logo-wrap">
            <img src="/logo.png" alt="" class="login-spiral" />
            <span class="hover-dot"></span>
          </span>
          <span class="logo">volute</span>
        </div>
        <div class="subtitle">
          {mode === "login" ? "Sign in to continue" : "Create an account"}
        </div>
      </div>

      <form onsubmit={handleSubmit}>
        <Input
          inputSize="md"
          type="text"
          placeholder="username"
          bind:value={username}
        />
        <Input
          inputSize="md"
          type="password"
          placeholder="password"
          bind:value={password}
          style="margin-top:8px"
        />
        {#if error}
          <div class="error">{error}</div>
        {/if}
        <button
          type="submit"
          disabled={loading || !username.trim() || !password.trim()}
          class="submit-btn"
          style:opacity={loading ? 0.5 : 1}
        >
          {loading ? "..." : mode === "login" ? "Sign in" : "Create account"}
        </button>
      </form>

      <div class="toggle">
        <button class="link-btn" onclick={() => { mode = mode === "login" ? "register" : "login"; error = ""; }}>
          {mode === "login" ? "Need an account? Register" : "Have an account? Sign in"}
        </button>
      </div>
    </div>
  </div>
{/if}

<style>
  .container {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100%;
    padding: 24px;
  }

  .card {
    width: 320px;
    padding: 32px;
    background: var(--bg-1);
    border: 1px solid var(--border);
    border-radius: var(--radius-lg);
  }

  .branding {
    margin-bottom: 24px;
    text-align: center;
  }

  .logo-row {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 4px;
    margin-bottom: 4px;
  }

  .logo-wrap {
    position: relative;
    width: 34px;
    height: 34px;
    flex-shrink: 0;
  }

  .login-spiral {
    width: 34px;
    height: 34px;
    filter: invert(1);
    transition: opacity 0.15s;
  }

  .hover-dot {
    position: absolute;
    inset: 0;
    margin: auto;
    width: 10px;
    height: 10px;
    border-radius: 50%;
    opacity: 0;
    transition: opacity 0.15s;
    animation: iridescent 3s ease-in-out infinite;
  }

  .card:hover .login-spiral {
    opacity: 0;
  }

  .card:hover .hover-dot {
    opacity: 1;
  }

  .logo {
    font-family: var(--display);
    font-size: 31px;
    font-weight: 300;
    color: var(--text-0);
    letter-spacing: 0.04em;
    margin-top: -4px;
  }

  .subtitle {
    color: var(--text-2);
    font-size: 13px;
  }
  .error {
    color: var(--red);
    font-size: 13px;
    margin-top: 8px;
  }

  .submit-btn {
    width: 100%;
    padding: 10px 16px;
    margin-top: 16px;
    background: var(--accent-dim);
    color: var(--accent);
    border-radius: var(--radius);
    font-size: 14px;
    font-weight: 500;
    font-family: inherit;
    border: none;
    cursor: pointer;
  }

  .link-btn {
    background: transparent;
    color: var(--text-2);
    font-size: 13px;
    font-family: inherit;
    border: none;
    cursor: pointer;
    padding: 0;
  }

  .toggle {
    margin-top: 16px;
    text-align: center;
  }

  .pending-msg {
    color: var(--yellow);
    margin-bottom: 16px;
  }
</style>
