// src/web/ui/src/components/mind/MindCard.svelte
<script lang="ts">
import type { Mind } from "@volute/api";
import { StatusBadge } from "@volute/ui";

let { mind }: { mind: Mind } = $props();
</script>

<a href={`/mind/${mind.name}`} class="card">
  <div class="header">
    <div class="header-left">
      {#if mind.avatar}
        <img
          src={`/api/minds/${encodeURIComponent(mind.name)}/avatar`}
          alt=""
          class="card-avatar"
        />
      {/if}
      <span class="name">{mind.displayName ?? mind.name}</span>
      {#if mind.displayName && mind.displayName !== mind.name}
        <span class="username">@{mind.name}</span>
      {/if}
    </div>
    {#if mind.stage === "seed"}
      <span class="seed-badge">seed</span>
    {/if}
    <StatusBadge status={mind.status} />
  </div>
  {#if mind.description}
    <p class="description">{mind.description}</p>
  {/if}
  <div class="meta">
    <span>:{mind.port}</span>
    {#each mind.channels.filter(ch => ch.name !== "web" && ch.status === "connected") as ch}
      <span class="channel-badge">{ch.displayName || ch.name}</span>
    {/each}
  </div>
</a>

<style>
  .card {
    display: block;
    padding: 20px;
    background: var(--bg-2);
    border: 1px solid var(--border);
    border-radius: var(--radius-lg);
    cursor: pointer;
    transition: all 0.15s ease;
  }

  .card:hover {
    border-color: var(--border-bright);
    background: var(--bg-3);
  }

  .header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 12px;
  }

  .header-left {
    display: flex;
    align-items: center;
    gap: 8px;
  }

  .card-avatar {
    width: 28px;
    height: 28px;
    border-radius: 50%;
    object-fit: cover;
  }

  .name {
    font-family: var(--display);
    font-size: 19px;
    font-weight: 400;
    color: var(--text-0);
  }

  .username {
    font-size: 13px;
    color: var(--text-2);
  }

  .description {
    font-size: 13px;
    color: var(--text-1);
    margin: 0 0 8px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .seed-badge {
    display: inline-flex;
    align-items: center;
    gap: 5px;
    padding: 2px 8px;
    border-radius: var(--radius);
    background: var(--yellow-bg);
    color: var(--yellow);
    font-size: 12px;
    font-weight: 500;
    letter-spacing: 0.02em;
    text-transform: uppercase;
  }

  .meta {
    display: flex;
    align-items: center;
    gap: 16px;
    color: var(--text-2);
    font-size: 13px;
  }

  .channel-badge {
    font-size: 11px;
    padding: 2px 6px;
    border-radius: var(--radius);
    background: var(--accent-dim);
    color: var(--accent);
  }
</style>

// src/web/frontend/src/components/MindCard.tsx
import type { Mind } from "../lib/api";
import { StatusBadge } from "./StatusBadge";

export function MindCard({ mind }: { mind: Mind }) {
  return (
    <a
      href={`#/mind/${mind.name}`}
      style={{
        display: "block",
        padding: 20,
        background: "var(--bg-2)",
        border: "1px solid var(--border)",
        borderRadius: "var(--radius-lg)",
        cursor: "pointer",
        transition: "all 0.15s ease",
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.borderColor = "var(--border-bright)";
        e.currentTarget.style.background = "var(--bg-3)";
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.borderColor = "var(--border)";
        e.currentTarget.style.background = "var(--bg-2)";
      }}
    >
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          marginBottom: 12,
        }}
      >
        <span
          style={{
            fontSize: 15,
            fontWeight: 600,
            color: "var(--text-0)",
          }}
        >
          {mind.name}
        </span>
        {mind.stage === "seed" && (
          <span
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 5,
              padding: "2px 8px",
              borderRadius: "var(--radius)",
              background: "rgba(251, 191, 36, 0.08)",
              color: "var(--yellow)",
              fontSize: 11,
              fontWeight: 500,
              letterSpacing: "0.02em",
              textTransform: "uppercase",
            }}
          >
            seed
          </span>
        )}
        <StatusBadge status={mind.status} />
      </div>
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 16,
          color: "var(--text-2)",
          fontSize: 12,
        }}
      >
        <span>:{mind.port}</span>
        {mind.channels
          .filter((ch) => ch.name !== "web" && ch.status === "connected")
          .map((ch) => (
            <span
              key={ch.name}
              style={{
                fontSize: 10,
                padding: "2px 6px",
                borderRadius: "var(--radius)",
                background: "var(--accent-dim)",
                color: "var(--accent)",
              }}
            >
              {ch.displayName || ch.name}
            </span>
          ))}
      </div>
    </a>
  );
}
