// src/web/frontend/src/components/Chat.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  type ContentBlock,
  fetchConversationMessages,
  fetchConversationMessagesById,
  fetchTyping,
  reportTyping,
  type VoluteEvent,
} from "../lib/api";
import { renderMarkdown } from "../lib/marked";
import { useChatSend } from "../lib/useStream";

type ChatEntry = { role: "user" | "assistant"; blocks: ContentBlock[]; senderName?: string };

function normalizeContent(content: ContentBlock[] | string): ContentBlock[] {
  if (Array.isArray(content)) return content;
  return [{ type: "text", text: String(content) }];
}

type ToolBlock = {
  name: string;
  input: unknown;
  output?: string;
  isError?: boolean;
};

export function Chat({
  name,
  username,
  conversationId,
  onConversationId,
  stage,
}: {
  name: string;
  username?: string;
  conversationId: string | null;
  onConversationId: (id: string) => void;
  stage?: "seed" | "sprouted";
}) {
  const [entries, setEntries] = useState<ChatEntry[]>([]);
  const [input, setInput] = useState("");
  const [sending, setSending] = useState(false);
  const [pendingImages, setPendingImages] = useState<
    Array<{ media_type: string; data: string; preview: string }>
  >([]);
  const scrollRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const fileRef = useRef<HTMLInputElement>(null);
  const convIdRef = useRef(conversationId);
  const typingTimerRef = useRef<number>(0);
  const [typingNames, setTypingNames] = useState<string[]>([]);
  const lastPollFingerprintRef = useRef("");

  const scrollToBottom = useCallback((force?: boolean) => {
    requestAnimationFrame(() => {
      const el = scrollRef.current;
      if (!el) return;
      if (force) {
        el.scrollTop = el.scrollHeight;
        return;
      }
      const isNearBottom = el.scrollHeight - el.scrollTop - el.clientHeight < 100;
      if (isNearBottom) {
        el.scrollTop = el.scrollHeight;
      }
    });
  }, []);

  const loadMessages = useCallback(
    (convId: string, forceScroll?: boolean) => {
      const fetchFn = name
        ? fetchConversationMessages(name, convId)
        : fetchConversationMessagesById(convId);
      return fetchFn
        .then((msgs) => {
          // Skip re-render if messages haven't changed (prevents scrollbar flicker from polling)
          const fingerprint = `${msgs.length}:${msgs[msgs.length - 1]?.id ?? ""}`;
          if (!forceScroll && fingerprint === lastPollFingerprintRef.current) return;
          lastPollFingerprintRef.current = fingerprint;

          const loaded: ChatEntry[] = msgs.map((m) => ({
            role: m.role as "user" | "assistant",
            blocks: normalizeContent(m.content),
            senderName: m.sender_name ?? undefined,
          }));
          setEntries(loaded);
          if (forceScroll) scrollToBottom(true);
        })
        .catch((e) => console.error("Failed to load messages:", e));
    },
    [name, scrollToBottom],
  );

  // Load existing messages when conversationId changes
  useEffect(() => {
    convIdRef.current = conversationId;
    lastPollFingerprintRef.current = "";
    if (!conversationId) {
      setEntries([]);
      return;
    }
    loadMessages(conversationId, true);
  }, [conversationId, loadMessages]);

  // Subscribe to SSE conversation events for real-time updates
  useEffect(() => {
    if (!conversationId || !name) return;
    const eventSource = new EventSource(
      `/api/minds/${encodeURIComponent(name)}/conversations/${encodeURIComponent(conversationId)}/events`,
    );
    eventSource.onmessage = (ev) => {
      if (!ev.data) return;
      let event: any;
      try {
        event = JSON.parse(ev.data);
      } catch (err) {
        console.warn("[chat] failed to parse SSE event:", err);
        return;
      }
      if (event.type === "message") {
        // New message arrived — reload conversation
        loadMessages(conversationId, false);
        scrollToBottom();
      }
    };
    // Reload messages on reconnect to catch anything missed during the gap
    eventSource.onopen = () => {
      loadMessages(conversationId, false);
    };
    return () => eventSource.close();
  }, [conversationId, name, loadMessages, scrollToBottom]);

  // Poll typing indicators
  useEffect(() => {
    if (!conversationId || !name) return;
    let cancelled = false;
    const poll = () => {
      fetchTyping(name, `volute:${conversationId}`)
        .then((names) => {
          if (cancelled) return;
          setTypingNames(names.filter((n) => n !== username));
        })
        .catch((err) => {
          if (!cancelled) console.warn("[chat] typing poll error:", err);
        });
    };
    poll();
    const id = setInterval(poll, 5000);
    return () => {
      cancelled = true;
      clearInterval(id);
    };
  }, [conversationId, name, username]);

  // Clear typing indicator on unmount
  useEffect(() => {
    return () => {
      if (convIdRef.current && name && username && typingTimerRef.current > 0) {
        reportTyping(name, `volute:${convIdRef.current}`, username, false);
      }
    };
  }, [name, username]);

  const onEvent = useCallback(
    (event: VoluteEvent) => {
      if (event.type === "meta") {
        convIdRef.current = event.conversationId;
        onConversationId(event.conversationId);
      }
      if (event.type === "done") {
        setSending(false);
      }
    },
    [onConversationId],
  );

  const { send } = useChatSend(name, onEvent);
  const colorMap = useMemo(() => buildSenderColorMap(entries), [entries]);

  const handleSend = async () => {
    const message = input.trim();
    if (!message && pendingImages.length === 0) return;
    if (sending) return;

    const images = pendingImages.map(({ media_type, data }) => ({
      media_type,
      data,
    }));

    // Build user blocks for optimistic UI
    const userBlocks: ContentBlock[] = [];
    if (message) {
      userBlocks.push({ type: "text", text: message });
    }
    for (const img of pendingImages) {
      userBlocks.push({
        type: "image",
        media_type: img.media_type,
        data: img.data,
      });
    }

    setInput("");
    setPendingImages([]);
    if (inputRef.current) {
      inputRef.current.style.height = "auto";
      inputRef.current.style.overflow = "hidden";
    }
    // Optimistic: show user's message immediately
    setEntries((prev) => [...prev, { role: "user", blocks: userBlocks, senderName: username }]);
    setSending(true);
    // Clear user's typing indicator
    if (convIdRef.current && name && username) {
      reportTyping(name, `volute:${convIdRef.current}`, username, false);
      typingTimerRef.current = 0;
    }
    scrollToBottom(true);

    try {
      await send(message, convIdRef.current ?? undefined, images.length > 0 ? images : undefined);
    } catch (err) {
      console.error("Failed to send message:", err);
      setEntries((prev) => [
        ...prev,
        {
          role: "assistant",
          blocks: [{ type: "text", text: "*Failed to send message. Please try again.*" }],
          senderName: "system",
        },
      ]);
      setSending(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleFiles = (files: FileList | null) => {
    if (!files) return;
    for (const file of Array.from(files)) {
      if (!file.type.startsWith("image/")) continue;
      const reader = new FileReader();
      reader.onload = () => {
        const result = reader.result as string;
        const base64 = result.split(",")[1];
        setPendingImages((prev) => [
          ...prev,
          { media_type: file.type, data: base64, preview: result },
        ]);
      };
      reader.readAsDataURL(file);
    }
  };

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        height: "100%",
      }}
    >
      {/* Orientation header */}
      {stage === "seed" && (
        <div
          style={{
            padding: "6px 12px",
            textAlign: "center",
            color: "var(--yellow)",
            fontSize: 11,
            fontWeight: 500,
            letterSpacing: "0.05em",
            textTransform: "uppercase",
            opacity: 0.6,
            borderBottom: "1px solid rgba(251, 191, 36, 0.1)",
          }}
        >
          orientation
        </div>
      )}
      {/* Messages */}
      <div
        ref={scrollRef}
        style={{
          flex: 1,
          overflow: "auto",
          padding: "16px 0",
        }}
      >
        {entries.length === 0 && (
          <div
            style={{
              color: "var(--text-2)",
              textAlign: "center",
              padding: 40,
              fontSize: 13,
            }}
          >
            Send a message to start chatting.
          </div>
        )}
        {entries.map((entry, i) => {
          // Render system divider messages (e.g. "[seed has sprouted]")
          if (
            entry.senderName === "system" &&
            entry.blocks.length === 1 &&
            entry.blocks[0].type === "text"
          ) {
            const text = entry.blocks[0].text;
            const dividerMatch = text.match(/^\[(.+)\]$/);
            if (dividerMatch) {
              return (
                <div
                  key={i}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 12,
                    margin: "20px 0",
                    color: "var(--text-2)",
                    fontSize: 11,
                    letterSpacing: "0.03em",
                  }}
                >
                  <div style={{ flex: 1, height: 1, background: "var(--border)" }} />
                  <span>{dividerMatch[1]}</span>
                  <div style={{ flex: 1, height: 1, background: "var(--border)" }} />
                </div>
              );
            }
          }
          return (
            <div
              key={i}
              style={{
                marginBottom: 16,
                animation: "fadeIn 0.2s ease both",
              }}
            >
              {entry.role === "user" ? (
                <UserMessage
                  blocks={entry.blocks}
                  senderName={entry.senderName}
                  color={entry.senderName ? colorMap.get(entry.senderName) : undefined}
                />
              ) : (
                <AssistantMessage
                  blocks={entry.blocks}
                  senderName={entry.senderName}
                  color={entry.senderName ? colorMap.get(entry.senderName) : undefined}
                />
              )}
            </div>
          );
        })}
      </div>

      {/* Image preview strip */}
      {pendingImages.length > 0 && (
        <div
          style={{
            display: "flex",
            gap: 8,
            padding: "8px 0",
            borderTop: "1px solid var(--border)",
            overflowX: "auto",
          }}
        >
          {pendingImages.map((img, i) => (
            <div key={i} style={{ position: "relative", flexShrink: 0 }}>
              <img
                src={img.preview}
                alt=""
                style={{
                  height: 60,
                  borderRadius: "var(--radius)",
                  border: "1px solid var(--border)",
                }}
              />
              <button
                onClick={() => setPendingImages((prev) => prev.filter((_, j) => j !== i))}
                style={{
                  position: "absolute",
                  top: -4,
                  right: -4,
                  width: 18,
                  height: 18,
                  borderRadius: "50%",
                  background: "var(--bg-3)",
                  color: "var(--text-1)",
                  fontSize: 11,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  border: "1px solid var(--border)",
                  cursor: "pointer",
                  padding: 0,
                }}
              >
                x
              </button>
            </div>
          ))}
        </div>
      )}

      {/* Typing indicator */}
      {typingNames.length > 0 && (
        <div
          style={{
            padding: "4px 0",
            fontSize: 12,
            color: "var(--text-2)",
            animation: "pulse 1.5s ease infinite",
          }}
        >
          {typingNames.length === 1
            ? `${typingNames[0]} is typing...`
            : `${typingNames.join(", ")} are typing...`}
        </div>
      )}

      {/* Hidden file input */}
      <input
        ref={fileRef}
        type="file"
        accept="image/*"
        multiple
        style={{ display: "none" }}
        onChange={(e) => handleFiles(e.target.files)}
      />

      {/* Input */}
      <div
        style={{
          borderTop: "1px solid var(--border)",
          padding: "12px 0 0",
          display: "flex",
          gap: 8,
        }}
      >
        <button
          onClick={() => fileRef.current?.click()}
          style={{
            padding: "0 10px",
            background: "var(--bg-2)",
            color: "var(--text-1)",
            borderRadius: "var(--radius)",
            fontSize: 16,
            border: "1px solid var(--border)",
            cursor: "pointer",
            flexShrink: 0,
          }}
        >
          +
        </button>
        <textarea
          ref={inputRef}
          value={input}
          onChange={(e) => {
            setInput(e.target.value);
            // Report typing (debounced to every 3s)
            if (convIdRef.current && name && username) {
              const now = Date.now();
              if (now - typingTimerRef.current > 3000) {
                typingTimerRef.current = now;
                reportTyping(name, `volute:${convIdRef.current}`, username, true);
              }
            }
          }}
          onKeyDown={handleKeyDown}
          onInput={(e) => {
            const el = e.currentTarget;
            el.style.height = "auto";
            const maxH = 120;
            el.style.height = `${Math.min(el.scrollHeight, maxH)}px`;
            el.style.overflow = el.scrollHeight > maxH ? "auto" : "hidden";
          }}
          placeholder="Send a message..."
          rows={1}
          style={{
            flex: 1,
            background: "var(--bg-2)",
            border: "1px solid var(--border)",
            borderRadius: "var(--radius)",
            padding: "10px 12px",
            color: "var(--text-0)",
            fontFamily: "var(--mono)",
            fontSize: 13,
            resize: "none",
            outline: "none",
            overflow: "hidden",
            transition: "border-color 0.15s",
          }}
          onFocus={(e) => (e.currentTarget.style.borderColor = "var(--border-bright)")}
          onBlur={(e) => {
            e.currentTarget.style.borderColor = "var(--border)";
            if (convIdRef.current && name && username && typingTimerRef.current > 0) {
              reportTyping(name, `volute:${convIdRef.current}`, username, false);
              typingTimerRef.current = 0;
            }
          }}
        />
        <button
          onClick={handleSend}
          disabled={sending || (!input.trim() && pendingImages.length === 0)}
          style={{
            padding: "0 16px",
            background:
              input.trim() || pendingImages.length > 0 ? "var(--accent-dim)" : "var(--bg-3)",
            color: input.trim() || pendingImages.length > 0 ? "var(--accent)" : "var(--text-2)",
            borderRadius: "var(--radius)",
            fontSize: 12,
            fontWeight: 500,
            transition: "all 0.15s",
          }}
        >
          {sending ? "sending..." : "send"}
        </button>
      </div>
    </div>
  );
}

const SENDER_COLORS = [
  "var(--blue)",
  "var(--purple)",
  "var(--yellow)",
  "var(--red)",
  "var(--accent)",
];

function buildSenderColorMap(entries: ChatEntry[]): Map<string, string> {
  const map = new Map<string, string>();
  for (const entry of entries) {
    const name = entry.senderName;
    if (name && !map.has(name)) {
      map.set(name, SENDER_COLORS[map.size % SENDER_COLORS.length]);
    }
  }
  return map;
}

function UserMessage({
  blocks,
  senderName,
  color,
}: {
  blocks: ContentBlock[];
  senderName?: string;
  color?: string;
}) {
  const label = senderName || "you";
  return (
    <div style={{ display: "flex", gap: 10 }}>
      <span
        style={{
          color: color ?? "var(--blue)",
          fontSize: 11,
          fontWeight: 600,
          flexShrink: 0,
          marginTop: 2,
          textTransform: "uppercase",
        }}
      >
        {label}
      </span>
      <div style={{ flex: 1, minWidth: 0 }}>
        {blocks.map((block, i) => {
          if (block.type === "text") {
            return (
              <div key={i} style={{ color: "var(--text-0)", whiteSpace: "pre-wrap" }}>
                {block.text}
              </div>
            );
          }
          if (block.type === "image") {
            return (
              <img
                key={i}
                src={`data:${block.media_type};base64,${block.data}`}
                alt=""
                style={{
                  maxWidth: 300,
                  maxHeight: 200,
                  borderRadius: "var(--radius)",
                  marginTop: 4,
                }}
              />
            );
          }
          return null;
        })}
      </div>
    </div>
  );
}

function AssistantMessage({
  blocks,
  senderName,
  color,
}: {
  blocks: ContentBlock[];
  senderName?: string;
  color?: string;
}) {
  // Build render items: text, tool pairs, images — in order
  const items: Array<
    | { kind: "text"; text: string }
    | { kind: "tool"; tool: ToolBlock }
    | { kind: "image"; media_type: string; data: string }
  > = [];

  for (let i = 0; i < blocks.length; i++) {
    const block = blocks[i];
    if (block.type === "text") {
      items.push({ kind: "text", text: block.text });
    } else if (block.type === "tool_use") {
      const tool: ToolBlock = { name: block.name, input: block.input };
      // Peek at next block for paired tool_result
      const next = blocks[i + 1];
      if (next && next.type === "tool_result") {
        tool.output = next.output;
        tool.isError = next.is_error;
        i++; // skip the tool_result
      }
      items.push({ kind: "tool", tool });
    } else if (block.type === "tool_result") {
      // Orphaned tool_result (not paired with tool_use) — skip
    } else if (block.type === "image") {
      items.push({
        kind: "image",
        media_type: block.media_type,
        data: block.data,
      });
    }
  }

  return (
    <div style={{ display: "flex", gap: 10 }}>
      <span
        style={{
          color: color ?? "var(--accent)",
          fontSize: 11,
          fontWeight: 600,
          flexShrink: 0,
          marginTop: 2,
          textTransform: "uppercase",
        }}
      >
        {senderName || "mind"}
      </span>
      <div style={{ flex: 1, minWidth: 0 }}>
        {items.map((item, j) => {
          if (item.kind === "tool") {
            return <ToolUseBlock key={j} tool={item.tool} />;
          }
          if (item.kind === "image") {
            return (
              <img
                key={j}
                src={`data:${item.media_type};base64,${item.data}`}
                alt=""
                style={{
                  maxWidth: 300,
                  maxHeight: 200,
                  borderRadius: "var(--radius)",
                  marginTop: 4,
                }}
              />
            );
          }
          // text
          return (
            <div key={j} style={{ color: "var(--text-0)" }}>
              <div
                className="markdown-body"
                // biome-ignore lint/security/noDangerouslySetInnerHtml: sanitized by DOMPurify
                dangerouslySetInnerHTML={{
                  __html: renderMarkdown(item.text),
                }}
              />
            </div>
          );
        })}
      </div>
    </div>
  );
}

function getToolSummary(tool: ToolBlock): { label: string; color: string } {
  const inp = tool.input as Record<string, unknown>;
  switch (tool.name) {
    case "Read":
      return { label: `Read ${inp.file_path ?? ""}`, color: "var(--blue)" };
    case "Write":
      return { label: `Write ${inp.file_path ?? ""}`, color: "var(--blue)" };
    case "Edit":
      return { label: `Edit ${inp.file_path ?? ""}`, color: "var(--blue)" };
    case "Glob":
      return { label: `Glob ${inp.pattern ?? ""}`, color: "var(--yellow)" };
    case "Grep":
      return {
        label: `Grep "${inp.pattern ?? ""}"${inp.path ? ` in ${inp.path}` : ""}`,
        color: "var(--yellow)",
      };
    case "Bash":
      return {
        label: `Bash: ${String(inp.command ?? "").split("\n")[0]}`,
        color: "var(--red)",
      };
    case "WebSearch":
      return { label: `Search: "${inp.query ?? ""}"`, color: "var(--purple)" };
    case "WebFetch":
      return { label: `Fetch: ${inp.url ?? ""}`, color: "var(--purple)" };
    case "Task":
      return { label: `Task: ${inp.description ?? ""}`, color: "var(--accent)" };
    default:
      return { label: tool.name, color: "var(--purple)" };
  }
}

function ToolUseBlock({ tool }: { tool: ToolBlock }) {
  const [open, setOpen] = useState(false);
  const summary = getToolSummary(tool);

  return (
    <div
      style={{
        marginBottom: 8,
        border: "1px solid var(--border)",
        borderRadius: "var(--radius)",
        overflow: "hidden",
        fontSize: 12,
      }}
    >
      <button
        onClick={() => setOpen(!open)}
        style={{
          width: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          padding: "6px 10px",
          background: "var(--bg-3)",
          color: summary.color,
          fontSize: 12,
          fontFamily: "var(--mono)",
          textAlign: "left",
        }}
      >
        <span
          style={{
            overflow: "hidden",
            textOverflow: "ellipsis",
            whiteSpace: "nowrap",
            flex: 1,
            minWidth: 0,
          }}
        >
          <span style={{ color: "var(--text-2)", marginRight: 6 }}>{open ? "▾" : "▸"}</span>
          {summary.label}
        </span>
        {tool.output !== undefined && (
          <span
            style={{
              color: tool.isError ? "var(--red)" : "var(--accent)",
              fontSize: 10,
              flexShrink: 0,
              marginLeft: 8,
            }}
          >
            {tool.isError ? "error" : "done"}
          </span>
        )}
      </button>
      {open && (
        <div style={{ padding: 10, background: "var(--bg-1)" }}>
          <div style={{ marginBottom: 6, color: "var(--text-2)" }}>input:</div>
          <pre
            style={{
              color: "var(--text-1)",
              whiteSpace: "pre-wrap",
              wordBreak: "break-all",
              fontSize: 11,
              lineHeight: 1.5,
            }}
          >
            {JSON.stringify(tool.input, null, 2)}
          </pre>
          {tool.output !== undefined && (
            <>
              <div
                style={{
                  marginTop: 8,
                  marginBottom: 6,
                  color: "var(--text-2)",
                }}
              >
                output:
              </div>
              <pre
                style={{
                  color: tool.isError ? "var(--red)" : "var(--text-1)",
                  whiteSpace: "pre-wrap",
                  wordBreak: "break-all",
                  fontSize: 11,
                  lineHeight: 1.5,
                  maxHeight: 200,
                  overflow: "auto",
                }}
              >
                {tool.output}
              </pre>
            </>
          )}
        </div>
      )}
    </div>
  );
}

// src/web/svelte/src/components/Chat.svelte
<script lang="ts">
import {
  type ContentBlock,
  fetchConversationMessages,
  fetchConversationMessagesById,
  fetchTyping,
  reportTyping,
} from "../lib/api";
import { renderMarkdown } from "../lib/markdown";
import { sendChat } from "../lib/streams";

let {
  name,
  username,
  conversationId,
  onConversationId,
  stage,
}: {
  name: string;
  username?: string;
  conversationId: string | null;
  onConversationId: (id: string) => void;
  stage?: "seed" | "sprouted";
} = $props();

type ChatEntry = { role: "user" | "assistant"; blocks: ContentBlock[]; senderName?: string };

type ToolBlock = {
  name: string;
  input: unknown;
  output?: string;
  isError?: boolean;
};

function normalizeContent(content: ContentBlock[] | string): ContentBlock[] {
  if (Array.isArray(content)) return content;
  return [{ type: "text", text: String(content) }];
}

let entries = $state<ChatEntry[]>([]);
let input = $state("");
let sending = $state(false);
let pendingImages = $state<Array<{ media_type: string; data: string; preview: string }>>([]);
let typingNames = $state<string[]>([]);
let scrollEl: HTMLDivElement;
let inputEl: HTMLTextAreaElement;
let fileEl: HTMLInputElement;
let typingTimer = 0;
let lastPollFingerprint = "";
let currentConvId = conversationId;

// Tool open state tracking
let openTools = $state<Set<number>>(new Set());

const SENDER_COLORS = [
  "var(--blue)",
  "var(--purple)",
  "var(--yellow)",
  "var(--red)",
  "var(--accent)",
];

let colorMap = $derived.by(() => {
  const map = new Map<string, string>();
  for (const entry of entries) {
    const n = entry.senderName;
    if (n && !map.has(n)) {
      map.set(n, SENDER_COLORS[map.size % SENDER_COLORS.length]);
    }
  }
  return map;
});

function scrollToBottom(force?: boolean) {
  requestAnimationFrame(() => {
    if (!scrollEl) return;
    if (force) {
      scrollEl.scrollTop = scrollEl.scrollHeight;
      return;
    }
    const isNearBottom = scrollEl.scrollHeight - scrollEl.scrollTop - scrollEl.clientHeight < 100;
    if (isNearBottom) {
      scrollEl.scrollTop = scrollEl.scrollHeight;
    }
  });
}

function loadMessages(convId: string, forceScroll?: boolean) {
  const fetchFn = name
    ? fetchConversationMessages(name, convId)
    : fetchConversationMessagesById(convId);
  return fetchFn
    .then((msgs) => {
      const fingerprint = `${msgs.length}:${msgs[msgs.length - 1]?.id ?? ""}`;
      if (!forceScroll && fingerprint === lastPollFingerprint) return;
      lastPollFingerprint = fingerprint;

      entries = msgs.map((m) => ({
        role: m.role as "user" | "assistant",
        blocks: normalizeContent(m.content),
        senderName: m.sender_name ?? undefined,
      }));
      if (forceScroll) scrollToBottom(true);
    })
    .catch((e) => console.error("Failed to load messages:", e));
}

// Load messages when conversationId changes
$effect(() => {
  currentConvId = conversationId;
  lastPollFingerprint = "";
  openTools = new Set();
  if (!conversationId) {
    entries = [];
    return;
  }
  loadMessages(conversationId, true);
});

// SSE subscription for real-time updates
$effect(() => {
  if (!conversationId || !name) return;
  const eventSource = new EventSource(
    `/api/minds/${encodeURIComponent(name)}/conversations/${encodeURIComponent(conversationId)}/events`,
  );
  eventSource.onmessage = (ev) => {
    if (!ev.data) return;
    try {
      const event = JSON.parse(ev.data);
      if (event.type === "message") {
        loadMessages(conversationId, false);
        scrollToBottom();
      }
    } catch (err) {
      console.warn("[chat] failed to parse SSE event:", err);
    }
  };
  eventSource.onopen = () => {
    loadMessages(conversationId, false);
  };
  return () => eventSource.close();
});

// Poll typing indicators
$effect(() => {
  if (!conversationId || !name) return;
  let cancelled = false;
  const poll = () => {
    fetchTyping(name, `volute:${conversationId}`)
      .then((names) => {
        if (cancelled) return;
        typingNames = names.filter((n) => n !== username);
      })
      .catch(() => {});
  };
  poll();
  const id = setInterval(poll, 5000);
  return () => {
    cancelled = true;
    clearInterval(id);
  };
});

// Clear typing on unmount
$effect(() => {
  return () => {
    if (currentConvId && name && username && typingTimer > 0) {
      reportTyping(name, `volute:${currentConvId}`, username, false);
    }
  };
});

async function handleSend() {
  const message = input.trim();
  if (!message && pendingImages.length === 0) return;
  if (sending) return;

  const images = pendingImages.map(({ media_type, data }) => ({ media_type, data }));

  // Build user blocks for optimistic UI
  const userBlocks: ContentBlock[] = [];
  if (message) {
    userBlocks.push({ type: "text", text: message });
  }
  for (const img of pendingImages) {
    userBlocks.push({ type: "image", media_type: img.media_type, data: img.data });
  }

  input = "";
  pendingImages = [];
  if (inputEl) {
    inputEl.style.height = "auto";
    inputEl.style.overflow = "hidden";
  }
  entries = [...entries, { role: "user", blocks: userBlocks, senderName: username }];
  sending = true;
  if (currentConvId && name && username) {
    reportTyping(name, `volute:${currentConvId}`, username, false);
    typingTimer = 0;
  }
  scrollToBottom(true);

  try {
    const result = await sendChat(
      name,
      message,
      currentConvId ?? undefined,
      images.length > 0 ? images : undefined,
    );
    currentConvId = result.conversationId;
    onConversationId(result.conversationId);
    sending = false;
  } catch (err) {
    console.error("Failed to send message:", err);
    entries = [
      ...entries,
      {
        role: "assistant",
        blocks: [{ type: "text", text: "*Failed to send message. Please try again.*" }],
        senderName: "system",
      },
    ];
    sending = false;
  }
}

function handleKeyDown(e: KeyboardEvent) {
  if (e.key === "Enter" && !e.shiftKey) {
    e.preventDefault();
    handleSend();
  }
}

function handleFiles(files: FileList | null) {
  if (!files) return;
  for (const file of Array.from(files)) {
    if (!file.type.startsWith("image/")) continue;
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      const base64 = result.split(",")[1];
      pendingImages = [...pendingImages, { media_type: file.type, data: base64, preview: result }];
    };
    reader.readAsDataURL(file);
  }
}

function handleInput(e: Event) {
  const el = e.currentTarget as HTMLTextAreaElement;
  // Report typing (debounced to every 3s)
  if (currentConvId && name && username) {
    const now = Date.now();
    if (now - typingTimer > 3000) {
      typingTimer = now;
      reportTyping(name, `volute:${currentConvId}`, username, true);
    }
  }
  // Auto-resize
  el.style.height = "auto";
  const maxH = 120;
  el.style.height = `${Math.min(el.scrollHeight, maxH)}px`;
  el.style.overflow = el.scrollHeight > maxH ? "auto" : "hidden";
}

function handleBlur() {
  if (currentConvId && name && username && typingTimer > 0) {
    reportTyping(name, `volute:${currentConvId}`, username, false);
    typingTimer = 0;
  }
}

function getToolSummary(tool: ToolBlock): { label: string; color: string } {
  const inp = tool.input as Record<string, unknown>;
  switch (tool.name) {
    case "Read":
      return { label: `Read ${inp.file_path ?? ""}`, color: "var(--blue)" };
    case "Write":
      return { label: `Write ${inp.file_path ?? ""}`, color: "var(--blue)" };
    case "Edit":
      return { label: `Edit ${inp.file_path ?? ""}`, color: "var(--blue)" };
    case "Glob":
      return { label: `Glob ${inp.pattern ?? ""}`, color: "var(--yellow)" };
    case "Grep":
      return {
        label: `Grep "${inp.pattern ?? ""}"${inp.path ? ` in ${inp.path}` : ""}`,
        color: "var(--yellow)",
      };
    case "Bash":
      return {
        label: `Bash: ${String(inp.command ?? "").split("\n")[0]}`,
        color: "var(--red)",
      };
    case "WebSearch":
      return { label: `Search: "${inp.query ?? ""}"`, color: "var(--purple)" };
    case "WebFetch":
      return { label: `Fetch: ${inp.url ?? ""}`, color: "var(--purple)" };
    case "Task":
      return { label: `Task: ${inp.description ?? ""}`, color: "var(--accent)" };
    default:
      return { label: tool.name, color: "var(--purple)" };
  }
}

function buildAssistantItems(
  blocks: ContentBlock[],
): Array<
  | { kind: "text"; text: string }
  | { kind: "tool"; tool: ToolBlock }
  | { kind: "image"; media_type: string; data: string }
> {
  const items: Array<
    | { kind: "text"; text: string }
    | { kind: "tool"; tool: ToolBlock }
    | { kind: "image"; media_type: string; data: string }
  > = [];

  for (let i = 0; i < blocks.length; i++) {
    const block = blocks[i];
    if (block.type === "text") {
      items.push({ kind: "text", text: block.text });
    } else if (block.type === "tool_use") {
      const tool: ToolBlock = { name: block.name, input: block.input };
      const next = blocks[i + 1];
      if (next && next.type === "tool_result") {
        tool.output = next.output;
        tool.isError = next.is_error;
        i++;
      }
      items.push({ kind: "tool", tool });
    } else if (block.type === "tool_result") {
      // Orphaned tool_result — skip
    } else if (block.type === "image") {
      items.push({ kind: "image", media_type: block.media_type, data: block.data });
    }
  }
  return items;
}

function toggleTool(idx: number) {
  const next = new Set(openTools);
  if (next.has(idx)) next.delete(idx);
  else next.add(idx);
  openTools = next;
}
</script>

<div class="chat">
  <!-- Orientation header -->
  {#if stage === "seed"}
    <div class="orientation-bar">orientation</div>
  {/if}

  <!-- Messages -->
  <div class="messages" bind:this={scrollEl}>
    {#if entries.length === 0}
      <div class="empty">Send a message to start chatting.</div>
    {/if}
    {#each entries as entry, i (i)}
      <!-- System divider -->
      {#if entry.senderName === "system" && entry.blocks.length === 1 && entry.blocks[0].type === "text"}
        {@const text = entry.blocks[0].text}
        {@const dividerMatch = text.match(/^\[(.+)\]$/)}
        {#if dividerMatch}
          <div class="divider">
            <div class="divider-line"></div>
            <span>{dividerMatch[1]}</span>
            <div class="divider-line"></div>
          </div>
        {:else if entry.role === "user"}
          <div class="entry">
            <span class="sender user" style:color={entry.senderName ? colorMap.get(entry.senderName) : "var(--blue)"}>{entry.senderName || "you"}</span>
            <div class="entry-content">
              <div class="user-text">{text}</div>
            </div>
          </div>
        {:else}
          <div class="entry">
            <span class="sender" style:color={entry.senderName ? colorMap.get(entry.senderName) : "var(--accent)"}>{entry.senderName || "mind"}</span>
            <div class="entry-content">
              <div class="markdown-body">{@html renderMarkdown(text)}</div>
            </div>
          </div>
        {/if}
      {:else}
        <div class="entry">
          {#if entry.role === "user"}
            <span class="sender user" style:color={entry.senderName ? colorMap.get(entry.senderName) : "var(--blue)"}>{entry.senderName || "you"}</span>
            <div class="entry-content">
              {#each entry.blocks as block}
                {#if block.type === "text"}
                  <div class="user-text">{block.text}</div>
                {:else if block.type === "image"}
                  <img src={`data:${block.media_type};base64,${block.data}`} alt="" class="chat-image" />
                {/if}
              {/each}
            </div>
          {:else}
            {@const items = buildAssistantItems(entry.blocks)}
            <span class="sender" style:color={entry.senderName ? colorMap.get(entry.senderName) : "var(--accent)"}>{entry.senderName || "mind"}</span>
            <div class="entry-content">
              {#each items as item, j}
                {#if item.kind === "text"}
                  <div class="markdown-body">{@html renderMarkdown(item.text)}</div>
                {:else if item.kind === "tool"}
                  {@const summary = getToolSummary(item.tool)}
                  {@const toolKey = i * 1000 + j}
                  {@const isOpen = openTools.has(toolKey)}
                  <div class="tool-block">
                    <button class="tool-header" onclick={() => toggleTool(toolKey)} style:color={summary.color}>
                      <span class="tool-label">
                        <span class="tool-arrow">{isOpen ? "\u25BE" : "\u25B8"}</span>
                        {summary.label}
                      </span>
                      {#if item.tool.output !== undefined}
                        <span class="tool-status" class:error={item.tool.isError}>
                          {item.tool.isError ? "error" : "done"}
                        </span>
                      {/if}
                    </button>
                    {#if isOpen}
                      <div class="tool-detail">
                        <div class="tool-section-label">input:</div>
                        <pre class="tool-pre">{JSON.stringify(item.tool.input, null, 2)}</pre>
                        {#if item.tool.output !== undefined}
                          <div class="tool-section-label" style="margin-top: 8px">output:</div>
                          <pre class="tool-pre tool-output" class:error={item.tool.isError}>{item.tool.output}</pre>
                        {/if}
                      </div>
                    {/if}
                  </div>
                {:else if item.kind === "image"}
                  <img src={`data:${item.media_type};base64,${item.data}`} alt="" class="chat-image" />
                {/if}
              {/each}
            </div>
          {/if}
        </div>
      {/if}
    {/each}
  </div>

  <!-- Image preview strip -->
  {#if pendingImages.length > 0}
    <div class="image-strip">
      {#each pendingImages as img, i (i)}
        <div class="image-preview">
          <img src={img.preview} alt="" class="preview-thumb" />
          <button class="remove-image" onclick={() => { pendingImages = pendingImages.filter((_, j) => j !== i); }}>x</button>
        </div>
      {/each}
    </div>
  {/if}

  <!-- Typing indicator -->
  {#if typingNames.length > 0}
    <div class="typing">
      {typingNames.length === 1
        ? `${typingNames[0]} is typing...`
        : `${typingNames.join(", ")} are typing...`}
    </div>
  {/if}

  <!-- Hidden file input -->
  <input
    bind:this={fileEl}
    type="file"
    accept="image/*"
    multiple
    style="display: none"
    onchange={(e) => handleFiles((e.currentTarget as HTMLInputElement).files)}
  />

  <!-- Input area -->
  <div class="input-area">
    <button class="attach-btn" onclick={() => fileEl?.click()}>+</button>
    <textarea
      bind:this={inputEl}
      bind:value={input}
      onkeydown={handleKeyDown}
      oninput={handleInput}
      onblur={handleBlur}
      placeholder="Send a message..."
      rows={1}
      class="chat-input"
    ></textarea>
    <button
      onclick={handleSend}
      disabled={sending || (!input.trim() && pendingImages.length === 0)}
      class="send-btn"
      class:active={!!input.trim() || pendingImages.length > 0}
    >
      {sending ? "sending..." : "send"}
    </button>
  </div>
</div>

<style>
  .chat {
    display: flex;
    flex-direction: column;
    height: 100%;
  }

  .orientation-bar {
    padding: 6px 12px;
    text-align: center;
    color: var(--yellow);
    font-size: 11px;
    font-weight: 500;
    letter-spacing: 0.05em;
    text-transform: uppercase;
    opacity: 0.6;
    border-bottom: 1px solid rgba(251, 191, 36, 0.1);
  }

  .messages {
    flex: 1;
    overflow: auto;
    padding: 16px 0;
  }

  .empty {
    color: var(--text-2);
    text-align: center;
    padding: 40px;
    font-size: 13px;
  }

  .entry {
    display: flex;
    gap: 10px;
    margin-bottom: 16px;
    animation: fadeIn 0.2s ease both;
  }

  .sender {
    font-size: 11px;
    font-weight: 600;
    flex-shrink: 0;
    margin-top: 2px;
    text-transform: uppercase;
  }

  .entry-content {
    flex: 1;
    min-width: 0;
  }

  .user-text {
    color: var(--text-0);
    white-space: pre-wrap;
  }

  .chat-image {
    max-width: 300px;
    max-height: 200px;
    border-radius: var(--radius);
    margin-top: 4px;
  }

  .divider {
    display: flex;
    align-items: center;
    gap: 12px;
    margin: 20px 0;
    color: var(--text-2);
    font-size: 11px;
    letter-spacing: 0.03em;
  }

  .divider-line {
    flex: 1;
    height: 1px;
    background: var(--border);
  }

  .tool-block {
    margin-bottom: 8px;
    border: 1px solid var(--border);
    border-radius: var(--radius);
    overflow: hidden;
    font-size: 12px;
  }

  .tool-header {
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 6px 10px;
    background: var(--bg-3);
    font-size: 12px;
    font-family: var(--mono);
    text-align: left;
  }

  .tool-label {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    flex: 1;
    min-width: 0;
  }

  .tool-arrow {
    color: var(--text-2);
    margin-right: 6px;
  }

  .tool-status {
    color: var(--accent);
    font-size: 10px;
    flex-shrink: 0;
    margin-left: 8px;
  }

  .tool-status.error {
    color: var(--red);
  }

  .tool-detail {
    padding: 10px;
    background: var(--bg-1);
  }

  .tool-section-label {
    margin-bottom: 6px;
    color: var(--text-2);
  }

  .tool-pre {
    color: var(--text-1);
    white-space: pre-wrap;
    word-break: break-all;
    font-size: 11px;
    line-height: 1.5;
  }

  .tool-output {
    max-height: 200px;
    overflow: auto;
  }

  .tool-output.error {
    color: var(--red);
  }

  .image-strip {
    display: flex;
    gap: 8px;
    padding: 8px 0;
    border-top: 1px solid var(--border);
    overflow-x: auto;
  }

  .image-preview {
    position: relative;
    flex-shrink: 0;
  }

  .preview-thumb {
    height: 60px;
    border-radius: var(--radius);
    border: 1px solid var(--border);
  }

  .remove-image {
    position: absolute;
    top: -4px;
    right: -4px;
    width: 18px;
    height: 18px;
    border-radius: 50%;
    background: var(--bg-3);
    color: var(--text-1);
    font-size: 11px;
    display: flex;
    align-items: center;
    justify-content: center;
    border: 1px solid var(--border);
    cursor: pointer;
    padding: 0;
  }

  .typing {
    padding: 4px 0;
    font-size: 12px;
    color: var(--text-2);
    animation: pulse 1.5s ease infinite;
  }

  .input-area {
    border-top: 1px solid var(--border);
    padding: 12px 0 0;
    display: flex;
    gap: 8px;
  }

  .attach-btn {
    padding: 0 10px;
    background: var(--bg-2);
    color: var(--text-1);
    border-radius: var(--radius);
    font-size: 16px;
    border: 1px solid var(--border);
    cursor: pointer;
    flex-shrink: 0;
  }

  .chat-input {
    flex: 1;
    background: var(--bg-2);
    border: 1px solid var(--border);
    border-radius: var(--radius);
    padding: 10px 12px;
    color: var(--text-0);
    font-family: var(--mono);
    font-size: 13px;
    resize: none;
    outline: none;
    overflow: hidden;
    transition: border-color 0.15s;
  }

  .chat-input:focus {
    border-color: var(--border-bright);
  }

  .send-btn {
    padding: 0 16px;
    background: var(--bg-3);
    color: var(--text-2);
    border-radius: var(--radius);
    font-size: 12px;
    font-weight: 500;
    transition: all 0.15s;
  }

  .send-btn.active {
    background: var(--accent-dim);
    color: var(--accent);
  }
</style>
