// src/web/frontend/src/components/History.tsx
import { useCallback, useEffect, useState } from "react";
import { fetchHistory, fetchHistoryChannels, type HistoryMessage } from "../lib/api";
import { renderMarkdown } from "../lib/marked";

const PAGE_SIZE = 50;

const selectStyle: React.CSSProperties = {
  background: "var(--bg-2)",
  color: "var(--text-0)",
  border: "1px solid var(--border)",
  borderRadius: "var(--radius)",
  padding: "4px 8px",
  fontSize: 12,
  fontFamily: "var(--mono)",
};

export function History({ name }: { name: string }) {
  const [messages, setMessages] = useState<HistoryMessage[]>([]);
  const [channels, setChannels] = useState<string[]>([]);
  const [channel, setChannel] = useState("");
  const [hasMore, setHasMore] = useState(true);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetchHistoryChannels(name)
      .then(setChannels)
      .catch(() => {});
  }, [name]);

  const load = useCallback(
    async (offset: number) => {
      setLoading(true);
      try {
        const rows = await fetchHistory(name, {
          channel: channel || undefined,
          limit: PAGE_SIZE,
          offset,
        });
        if (offset === 0) {
          setMessages(rows);
        } else {
          setMessages((prev) => [...prev, ...rows]);
        }
        setHasMore(rows.length === PAGE_SIZE);
      } catch {
        // ignore
      }
      setLoading(false);
    },
    [name, channel],
  );

  useEffect(() => {
    load(0);
  }, [load]);

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%", overflow: "hidden" }}>
      {/* Filters */}
      <div
        style={{
          display: "flex",
          gap: 12,
          padding: "0 0 12px",
          borderBottom: "1px solid var(--border)",
          flexShrink: 0,
        }}
      >
        <select value={channel} onChange={(e) => setChannel(e.target.value)} style={selectStyle}>
          <option value="">all channels</option>
          {channels.map((ch) => (
            <option key={ch} value={ch}>
              {ch}
            </option>
          ))}
        </select>
      </div>

      {/* Messages */}
      <div style={{ flex: 1, overflow: "auto", paddingTop: 12 }}>
        {messages.length === 0 && !loading && (
          <div style={{ color: "var(--text-2)", textAlign: "center", padding: 40, fontSize: 13 }}>
            No messages found.
          </div>
        )}
        {messages.map((msg) => (
          <HistoryEntry key={msg.id} msg={msg} name={name} />
        ))}
        {hasMore && (
          <div style={{ padding: "16px 0", textAlign: "center" }}>
            <button
              onClick={() => load(messages.length)}
              disabled={loading}
              style={{
                padding: "6px 16px",
                background: "var(--bg-3)",
                color: "var(--text-1)",
                borderRadius: "var(--radius)",
                fontSize: 12,
                opacity: loading ? 0.5 : 1,
              }}
            >
              {loading ? "loading..." : "load more"}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

function HistoryEntry({ msg, name }: { msg: HistoryMessage; name: string }) {
  const isMind = msg.sender === name;
  const date = new Date(msg.created_at);
  const time = date.toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  return (
    <div style={{ marginBottom: 16, animation: "fadeIn 0.2s ease both" }}>
      <div style={{ display: "flex", gap: 10 }}>
        <span
          style={{
            color: !isMind ? "var(--blue)" : "var(--accent)",
            fontSize: 11,
            fontWeight: 600,
            flexShrink: 0,
            marginTop: 2,
            textTransform: "uppercase",
          }}
        >
          {!isMind ? (msg.sender ?? "user") : "mind"}
        </span>
        <div style={{ flex: 1, minWidth: 0 }}>
          {!isMind ? (
            <div style={{ color: "var(--text-0)", whiteSpace: "pre-wrap" }}>{msg.content}</div>
          ) : (
            <div
              className="markdown-body"
              // biome-ignore lint/security/noDangerouslySetInnerHtml: sanitized by DOMPurify
              dangerouslySetInnerHTML={{
                __html: renderMarkdown(msg.content),
              }}
            />
          )}
        </div>
        <div
          style={{
            flexShrink: 0,
            display: "flex",
            flexDirection: "column",
            alignItems: "flex-end",
            gap: 2,
          }}
        >
          <span style={{ fontSize: 10, color: "var(--text-2)" }}>{time}</span>
          <span
            style={{
              fontSize: 10,
              color: "var(--text-2)",
              background: "var(--bg-3)",
              padding: "1px 6px",
              borderRadius: "var(--radius)",
            }}
          >
            {msg.channel}
          </span>
        </div>
      </div>
    </div>
  );
}

// src/web/svelte/src/components/History.svelte
<script lang="ts">
import { fetchHistory, fetchHistoryChannels, type HistoryMessage } from "../lib/api";
import { renderMarkdown } from "../lib/markdown";

let { name }: { name: string } = $props();

const PAGE_SIZE = 50;

let messages = $state<HistoryMessage[]>([]);
let channels = $state<string[]>([]);
let channel = $state("");
let hasMore = $state(true);
let loading = $state(false);

async function load(filterChannel: string, offset: number) {
  loading = true;
  try {
    const rows = await fetchHistory(name, {
      channel: filterChannel || undefined,
      limit: PAGE_SIZE,
      offset,
    });
    if (offset === 0) {
      messages = rows;
    } else {
      messages = [...messages, ...rows];
    }
    hasMore = rows.length === PAGE_SIZE;
  } catch {
    // ignore
  }
  loading = false;
}

$effect(() => {
  fetchHistoryChannels(name)
    .then((ch) => {
      channels = ch;
    })
    .catch(() => {});
});

$effect(() => {
  load(channel, 0);
});

function formatTime(dateStr: string): string {
  const date = new Date(dateStr);
  return date.toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}
</script>

<div class="history">
  <!-- Filters -->
  <div class="filters">
    <select bind:value={channel} class="channel-select">
      <option value="">all channels</option>
      {#each channels as ch}
        <option value={ch}>{ch}</option>
      {/each}
    </select>
  </div>

  <!-- Messages -->
  <div class="messages">
    {#if messages.length === 0 && !loading}
      <div class="empty">No messages found.</div>
    {/if}
    {#each messages as msg (msg.id)}
      {@const isMind = msg.sender === name}
      <div class="entry">
        <div class="entry-row">
          <span class="sender" class:mind={isMind} class:user={!isMind}>
            {!isMind ? (msg.sender ?? "user") : "mind"}
          </span>
          <div class="content">
            {#if !isMind}
              <div class="user-text">{msg.content}</div>
            {:else}
              <div class="markdown-body">
                {@html renderMarkdown(msg.content)}
              </div>
            {/if}
          </div>
          <div class="meta">
            <span class="time">{formatTime(msg.created_at)}</span>
            <span class="channel-tag">{msg.channel}</span>
          </div>
        </div>
      </div>
    {/each}
    {#if hasMore}
      <div class="load-more">
        <button
          onclick={() => load(channel, messages.length)}
          disabled={loading}
          class="load-more-btn"
          style:opacity={loading ? 0.5 : 1}
        >
          {loading ? "loading..." : "load more"}
        </button>
      </div>
    {/if}
  </div>
</div>

<style>
  .history {
    display: flex;
    flex-direction: column;
    height: 100%;
    overflow: hidden;
  }

  .filters {
    display: flex;
    gap: 12px;
    padding: 0 0 12px;
    border-bottom: 1px solid var(--border);
    flex-shrink: 0;
  }

  .channel-select {
    background: var(--bg-2);
    color: var(--text-0);
    border: 1px solid var(--border);
    border-radius: var(--radius);
    padding: 4px 8px;
    font-size: 12px;
    font-family: var(--mono);
  }

  .messages {
    flex: 1;
    overflow: auto;
    padding-top: 12px;
  }

  .empty {
    color: var(--text-2);
    text-align: center;
    padding: 40px;
    font-size: 13px;
  }

  .entry {
    margin-bottom: 16px;
    animation: fadeIn 0.2s ease both;
  }

  .entry-row {
    display: flex;
    gap: 10px;
  }

  .sender {
    font-size: 11px;
    font-weight: 600;
    flex-shrink: 0;
    margin-top: 2px;
    text-transform: uppercase;
  }

  .sender.mind {
    color: var(--accent);
  }

  .sender.user {
    color: var(--blue);
  }

  .content {
    flex: 1;
    min-width: 0;
  }

  .user-text {
    color: var(--text-0);
    white-space: pre-wrap;
  }

  .meta {
    flex-shrink: 0;
    display: flex;
    flex-direction: column;
    align-items: flex-end;
    gap: 2px;
  }

  .time {
    font-size: 10px;
    color: var(--text-2);
  }

  .channel-tag {
    font-size: 10px;
    color: var(--text-2);
    background: var(--bg-3);
    padding: 1px 6px;
    border-radius: var(--radius);
  }

  .load-more {
    padding: 16px 0;
    text-align: center;
  }

  .load-more-btn {
    padding: 6px 16px;
    background: var(--bg-3);
    color: var(--text-1);
    border-radius: var(--radius);
    font-size: 12px;
  }
</style>
