// src/web/frontend/src/App.tsx
import { useEffect, useState } from "react";
import { LoginPage } from "./components/LoginPage";
import { SystemLogs } from "./components/SystemLogs";
import { UpdateBanner } from "./components/UpdateBanner";
import { UserManagement } from "./components/UserManagement";
import { type AuthUser, fetchMe, logout } from "./lib/auth";
import { Chats } from "./pages/Chats";
import { Dashboard } from "./pages/Dashboard";
import { Home } from "./pages/Home";
import { MindDetail } from "./pages/MindDetail";

function parseHash(): { page: string; name?: string; conversationId?: string; mindName?: string } {
  const hash = window.location.hash.slice(1) || "/";
  if (hash === "/" || hash === "") return { page: "home" };
  if (hash === "/minds") return { page: "minds" };
  if (hash === "/chats") return { page: "chats" };
  if (hash === "/logs") return { page: "logs" };
  const chatsMatch = hash.match(/^\/chats\/(.+)$/);
  if (chatsMatch) return { page: "chats", conversationId: chatsMatch[1] };
  const chatsMindMatch = hash.match(/^\/chats\?mind=(.+)$/);
  if (chatsMindMatch) return { page: "chats", mindName: decodeURIComponent(chatsMindMatch[1]) };
  const match = hash.match(/^\/mind\/(.+)$/);
  if (match) return { page: "mind", name: match[1] };
  return { page: "home" };
}

export function App() {
  const [route, setRoute] = useState(parseHash);
  const [user, setUser] = useState<AuthUser | null>(null);
  const [authChecked, setAuthChecked] = useState(false);
  const [showUsers, setShowUsers] = useState(false);

  useEffect(() => {
    fetchMe().then((u) => {
      setUser(u);
      setAuthChecked(true);
    });
  }, []);

  useEffect(() => {
    const handler = () => {
      setRoute(parseHash());
      setShowUsers(false);
    };
    window.addEventListener("hashchange", handler);
    return () => window.removeEventListener("hashchange", handler);
  }, []);

  const handleLogout = async () => {
    await logout();
    setUser(null);
  };

  if (!authChecked) {
    return (
      <>
        <style>{globalStyles}</style>
        <div className="app">
          <div style={{ color: "var(--text-2)", padding: 24, textAlign: "center" }}>Loading...</div>
        </div>
      </>
    );
  }

  if (!user) {
    return (
      <>
        <style>{globalStyles}</style>
        <div className="app" style={{ height: "100%" }}>
          <LoginPage onAuth={setUser} />
        </div>
      </>
    );
  }

  return (
    <>
      <style>{globalStyles}</style>
      <div className="app">
        {user.role === "admin" && <UpdateBanner />}
        <header className="app-header">
          <a href="#/" className="logo">
            <span className="logo-symbol">&gt;</span> volute
          </a>
          {route.page === "mind" && route.name && (
            <nav className="breadcrumb">
              <span className="breadcrumb-sep">/</span>
              <span className="breadcrumb-name">{route.name}</span>
            </nav>
          )}
          {route.page === "minds" && (
            <nav className="breadcrumb">
              <span className="breadcrumb-sep">/</span>
              <span className="breadcrumb-name">minds</span>
            </nav>
          )}
          {route.page === "chats" && (
            <nav className="breadcrumb">
              <span className="breadcrumb-sep">/</span>
              <span className="breadcrumb-name">chat</span>
            </nav>
          )}
          {route.page === "logs" && (
            <nav className="breadcrumb">
              <span className="breadcrumb-sep">/</span>
              <span className="breadcrumb-name">system logs</span>
            </nav>
          )}
          <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 12 }}>
            <NavLink href="#/chats" active={route.page === "chats"}>
              chat
            </NavLink>
            <NavLink href="#/minds" active={route.page === "minds" || route.page === "mind"}>
              minds
            </NavLink>
            <UserMenu
              username={user.username}
              isAdmin={user.role === "admin"}
              onLogout={handleLogout}
              onUsers={() => setShowUsers(!showUsers)}
              currentPage={route.page}
            />
          </div>
        </header>
        <main
          className="app-main"
          style={
            route.page === "chats" && !showUsers ? { padding: 0, overflow: "hidden" } : undefined
          }
        >
          {showUsers ? (
            <UserManagement onClose={() => setShowUsers(false)} />
          ) : (
            <>
              {route.page === "home" && <Home username={user.username} />}
              {route.page === "minds" && <Dashboard />}
              {route.page === "chats" && (
                <Chats
                  conversationId={route.conversationId}
                  mindName={route.mindName}
                  username={user.username}
                />
              )}
              {route.page === "mind" && route.name && <MindDetail name={route.name} />}
              {route.page === "logs" && <SystemLogs />}
            </>
          )}
        </main>
      </div>
    </>
  );
}

function NavLink({
  href,
  active,
  children,
}: {
  href: string;
  active: boolean;
  children: React.ReactNode;
}) {
  return (
    <a
      href={href}
      style={{
        color: active ? "var(--accent)" : "var(--text-2)",
        fontSize: 12,
        fontFamily: "var(--mono)",
        transition: "color 0.15s",
      }}
      onMouseEnter={(e) => {
        if (!active) e.currentTarget.style.color = "var(--text-0)";
      }}
      onMouseLeave={(e) => {
        if (!active) e.currentTarget.style.color = "var(--text-2)";
      }}
    >
      {children}
    </a>
  );
}

function UserMenu({
  username,
  isAdmin,
  onLogout,
  onUsers,
  currentPage,
}: {
  username: string;
  isAdmin: boolean;
  onLogout: () => void;
  onUsers: () => void;
  currentPage: string;
}) {
  const [open, setOpen] = useState(false);

  return (
    <div style={{ position: "relative" }}>
      <button
        onClick={() => setOpen(!open)}
        style={{
          background: "transparent",
          color: "var(--text-2)",
          fontSize: 12,
          fontFamily: "var(--mono)",
          border: "none",
          cursor: "pointer",
          transition: "color 0.15s",
          display: "flex",
          alignItems: "center",
          gap: 4,
        }}
        onMouseEnter={(e) => (e.currentTarget.style.color = "var(--text-0)")}
        onMouseLeave={(e) => {
          if (!open) e.currentTarget.style.color = "var(--text-2)";
        }}
      >
        {username}
        <span style={{ fontSize: 8 }}>{open ? "\u25B2" : "\u25BC"}</span>
      </button>
      {open && (
        <>
          <div style={{ position: "fixed", inset: 0, zIndex: 99 }} onClick={() => setOpen(false)} />
          <div
            style={{
              position: "absolute",
              right: 0,
              top: "100%",
              marginTop: 6,
              background: "var(--bg-2)",
              border: "1px solid var(--border)",
              borderRadius: "var(--radius)",
              padding: "4px 0",
              minWidth: 120,
              zIndex: 100,
            }}
          >
            {isAdmin && (
              <button
                onClick={() => {
                  window.location.hash = "#/logs";
                  setOpen(false);
                }}
                style={{
                  display: "block",
                  width: "100%",
                  padding: "6px 12px",
                  fontSize: 12,
                  color: currentPage === "logs" ? "var(--accent)" : "var(--text-1)",
                  background: "transparent",
                  textAlign: "left",
                  fontFamily: "var(--mono)",
                  transition: "background 0.1s",
                }}
                onMouseEnter={(e) => (e.currentTarget.style.background = "var(--bg-3)")}
                onMouseLeave={(e) => (e.currentTarget.style.background = "transparent")}
              >
                system logs
              </button>
            )}
            {isAdmin && (
              <button
                onClick={() => {
                  onUsers();
                  setOpen(false);
                }}
                style={{
                  display: "block",
                  width: "100%",
                  padding: "6px 12px",
                  fontSize: 12,
                  color: "var(--text-1)",
                  background: "transparent",
                  textAlign: "left",
                  fontFamily: "var(--mono)",
                  transition: "background 0.1s",
                }}
                onMouseEnter={(e) => (e.currentTarget.style.background = "var(--bg-3)")}
                onMouseLeave={(e) => (e.currentTarget.style.background = "transparent")}
              >
                manage users
              </button>
            )}
            {isAdmin && (
              <div
                style={{
                  borderTop: "1px solid var(--border)",
                  margin: "4px 0",
                }}
              />
            )}
            <button
              onClick={() => {
                onLogout();
                setOpen(false);
              }}
              style={{
                display: "block",
                width: "100%",
                padding: "6px 12px",
                fontSize: 12,
                color: "var(--text-2)",
                background: "transparent",
                textAlign: "left",
                fontFamily: "var(--mono)",
                transition: "background 0.1s",
              }}
              onMouseEnter={(e) => (e.currentTarget.style.background = "var(--bg-3)")}
              onMouseLeave={(e) => (e.currentTarget.style.background = "transparent")}
            >
              logout
            </button>
          </div>
        </>
      )}
    </div>
  );
}

const globalStyles = `
  :root {
    --bg-0: #0a0c0f;
    --bg-1: #11141a;
    --bg-2: #181c24;
    --bg-3: #1f2430;
    --border: #2a3040;
    --border-bright: #3a4560;
    --text-0: #e8ecf4;
    --text-1: #a0aabb;
    --text-2: #6a7588;
    --accent: #4ade80;
    --accent-dim: #22613e;
    --accent-bg: rgba(74, 222, 128, 0.08);
    --red: #f87171;
    --red-dim: #7f1d1d;
    --yellow: #fbbf24;
    --yellow-dim: #78350f;
    --blue: #60a5fa;
    --purple: #c084fc;
    --mono: 'IBM Plex Mono', 'SF Mono', 'Fira Code', monospace;
    --radius: 6px;
    --radius-lg: 10px;
  }

  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }

  html, body, #root {
    height: 100%;
    background: var(--bg-0);
    color: var(--text-0);
    font-family: var(--mono);
    font-size: 13px;
    line-height: 1.6;
    -webkit-font-smoothing: antialiased;
  }

  ::selection {
    background: var(--accent-dim);
    color: var(--accent);
  }

  ::-webkit-scrollbar {
    width: 6px;
    height: 6px;
  }
  ::-webkit-scrollbar-track {
    background: transparent;
  }
  ::-webkit-scrollbar-thumb {
    background: var(--border);
    border-radius: 3px;
  }
  ::-webkit-scrollbar-thumb:hover {
    background: var(--border-bright);
  }

  a {
    color: inherit;
    text-decoration: none;
  }

  button {
    font-family: var(--mono);
    cursor: pointer;
    border: none;
  }

  button:focus {
    outline: none;
  }

  button:focus-visible {
    outline: 1px solid var(--accent);
    outline-offset: 2px;
  }

  a:focus-visible {
    outline: 1px solid var(--accent);
    outline-offset: 2px;
  }

  .app {
    height: 100%;
    display: flex;
    flex-direction: column;
  }

  .app-header {
    display: flex;
    align-items: center;
    gap: 0;
    padding: 0 24px;
    height: 48px;
    background: var(--bg-1);
    border-bottom: 1px solid var(--border);
    flex-shrink: 0;
  }

  .logo {
    font-family: var(--mono);
    font-size: 15px;
    font-weight: 600;
    letter-spacing: -0.02em;
    color: var(--text-0);
    display: flex;
    align-items: center;
    gap: 0;
  }

  .logo-symbol {
    color: var(--accent);
    margin-right: 6px;
  }

  .logo:hover .logo-symbol {
    text-shadow: 0 0 8px var(--accent);
  }

  .breadcrumb {
    display: flex;
    align-items: center;
    font-size: 13px;
  }

  .breadcrumb-sep {
    color: var(--text-2);
    margin: 0 8px;
  }

  .breadcrumb-name {
    color: var(--text-1);
  }

  .app-main {
    flex: 1;
    overflow: auto;
    padding: 24px;
  }

  @keyframes fadeIn {
    from { opacity: 0; transform: translateY(6px); }
    to { opacity: 1; transform: translateY(0); }
  }

  @keyframes pulse {
    0%, 100% { opacity: 1; }
    50% { opacity: 0.5; }
  }

  @keyframes slideIn {
    from { opacity: 0; transform: translateX(-8px); }
    to { opacity: 1; transform: translateX(0); }
  }

  /* Markdown rendering */
  .markdown-body {
    word-break: break-word;
    color: var(--text-0);
    line-height: 1.6;
  }
  .markdown-body p {
    margin: 0 0 8px;
  }
  .markdown-body p:last-child {
    margin-bottom: 0;
  }
  .markdown-body pre {
    background: var(--bg-3);
    border: 1px solid var(--border);
    border-radius: var(--radius);
    padding: 10px 12px;
    overflow-x: auto;
    margin: 8px 0;
    font-size: 12px;
    line-height: 1.5;
  }
  .markdown-body code {
    font-family: var(--mono);
    font-size: 12px;
    background: var(--bg-3);
    padding: 1px 4px;
    border-radius: 3px;
  }
  .markdown-body pre code {
    background: none;
    padding: 0;
  }
  .markdown-body a {
    color: var(--blue);
    text-decoration: underline;
  }
  .markdown-body ul, .markdown-body ol {
    margin: 4px 0;
    padding-left: 20px;
  }
  .markdown-body li {
    margin: 2px 0;
  }
  .markdown-body h1, .markdown-body h2, .markdown-body h3,
  .markdown-body h4, .markdown-body h5, .markdown-body h6 {
    margin: 12px 0 6px;
    font-weight: 600;
    color: var(--text-0);
  }
  .markdown-body h1 { font-size: 18px; }
  .markdown-body h2 { font-size: 16px; }
  .markdown-body h3 { font-size: 14px; }
  .markdown-body blockquote {
    border-left: 3px solid var(--border-bright);
    margin: 8px 0;
    padding: 4px 12px;
    color: var(--text-1);
  }
  .markdown-body table {
    border-collapse: collapse;
    margin: 8px 0;
  }
  .markdown-body th, .markdown-body td {
    border: 1px solid var(--border);
    padding: 6px 10px;
    font-size: 12px;
  }
  .markdown-body th {
    background: var(--bg-3);
    font-weight: 600;
  }
  .markdown-body hr {
    border: none;
    border-top: 1px solid var(--border);
    margin: 12px 0;
  }
`;

// src/web/svelte/src/App.svelte
<script lang="ts">
import LoginPage from "./components/LoginPage.svelte";
import SystemLogs from "./components/SystemLogs.svelte";
import UpdateBanner from "./components/UpdateBanner.svelte";
import UserManagement from "./components/UserManagement.svelte";
import { fetchSystemInfo } from "./lib/api";
import { type AuthUser, fetchMe, logout } from "./lib/auth";
import Chats from "./pages/Chats.svelte";
import Dashboard from "./pages/Dashboard.svelte";
import Home from "./pages/Home.svelte";
import MindDetail from "./pages/MindDetail.svelte";

type Route = {
  page: string;
  name?: string;
  conversationId?: string;
  mindName?: string;
};

function parseHash(): Route {
  const hash = window.location.hash.slice(1) || "/";
  if (hash === "/" || hash === "") return { page: "home" };
  if (hash === "/minds") return { page: "minds" };
  if (hash === "/chats") return { page: "chats" };
  if (hash === "/logs") return { page: "logs" };
  const chatsMatch = hash.match(/^\/chats\/(.+)$/);
  if (chatsMatch) return { page: "chats", conversationId: chatsMatch[1] };
  const chatsMindMatch = hash.match(/^\/chats\?mind=(.+)$/);
  if (chatsMindMatch) return { page: "chats", mindName: decodeURIComponent(chatsMindMatch[1]) };
  const match = hash.match(/^\/mind\/(.+)$/);
  if (match) return { page: "mind", name: match[1] };
  return { page: "home" };
}

let route = $state<Route>(parseHash());
let user = $state<AuthUser | null>(null);
let authChecked = $state(false);
let showUsers = $state(false);
let systemName = $state<string | null>(null);
let userMenuOpen = $state(false);

$effect(() => {
  fetchMe().then((u) => {
    user = u;
    authChecked = true;
    if (u) {
      fetchSystemInfo().then((info) => {
        systemName = info.system;
      });
    }
  });
});

$effect(() => {
  const handler = () => {
    route = parseHash();
    showUsers = false;
  };
  window.addEventListener("hashchange", handler);
  return () => window.removeEventListener("hashchange", handler);
});

async function handleLogout() {
  await logout();
  user = null;
}

function handleAuth(u: AuthUser) {
  user = u;
  fetchSystemInfo().then((info) => {
    systemName = info.system;
  });
}

const breadcrumbLabel: Record<string, string> = {
  mind: "",
  minds: "minds",
  chats: "chat",
  logs: "system logs",
};
</script>

{#if !authChecked}
  <div class="app">
    <div class="loading">Loading...</div>
  </div>
{:else if !user}
  <div class="app full-height">
    <LoginPage onAuth={handleAuth} />
  </div>
{:else}
  <div class="app">
    {#if user.role === "admin"}
      <UpdateBanner />
    {/if}
    <header class="app-header">
      <a href="#/" class="logo">
        <span class="logo-symbol">&gt;</span> volute
        {#if systemName}
          <span class="system-name"> &middot; {systemName}</span>
        {/if}
      </a>
      {#if route.page === "mind" && route.name}
        <nav class="breadcrumb">
          <span class="breadcrumb-sep">/</span>
          <span class="breadcrumb-name">{route.name}</span>
        </nav>
      {:else if breadcrumbLabel[route.page]}
        <nav class="breadcrumb">
          <span class="breadcrumb-sep">/</span>
          <span class="breadcrumb-name">{breadcrumbLabel[route.page]}</span>
        </nav>
      {/if}
      <div class="header-right">
        <a href="#/chats" class="nav-link" class:active={route.page === "chats"}>chat</a>
        <a href="#/minds" class="nav-link" class:active={route.page === "minds" || route.page === "mind"}>minds</a>
        <div class="user-menu">
          <button class="user-menu-button" class:open={userMenuOpen} onclick={() => userMenuOpen = !userMenuOpen}>
            {user.username}
            <span class="caret">{userMenuOpen ? "\u25B2" : "\u25BC"}</span>
          </button>
          {#if userMenuOpen}
            <!-- svelte-ignore a11y_no_static_element_interactions -->
            <div class="overlay" onclick={() => userMenuOpen = false} onkeydown={() => {}}></div>
            <div class="dropdown">
              {#if user.role === "admin"}
                <button class="dropdown-item" class:active={route.page === "logs"} onclick={() => { window.location.hash = "#/logs"; userMenuOpen = false; }}>
                  system logs
                </button>
                <button class="dropdown-item" onclick={() => { showUsers = !showUsers; userMenuOpen = false; }}>
                  manage users
                </button>
                <div class="dropdown-divider"></div>
              {/if}
              <button class="dropdown-item muted" onclick={() => { handleLogout(); userMenuOpen = false; }}>
                logout
              </button>
            </div>
          {/if}
        </div>
      </div>
    </header>
    <main class="app-main" class:no-padding={route.page === "chats" && !showUsers}>
      {#if showUsers}
        <UserManagement onClose={() => showUsers = false} />
      {:else if route.page === "home"}
        <Home username={user.username} />
      {:else if route.page === "minds"}
        <Dashboard />
      {:else if route.page === "chats"}
        <Chats
          conversationId={route.conversationId}
          mindName={route.mindName}
          username={user.username}
        />
      {:else if route.page === "mind" && route.name}
        <MindDetail name={route.name} />
      {:else if route.page === "logs"}
        <SystemLogs />
      {/if}
    </main>
  </div>
{/if}

<style>
  .loading {
    color: var(--text-2);
    padding: 24px;
    text-align: center;
  }

  .full-height {
    height: 100%;
  }

  .system-name {
    color: var(--text-2);
    font-weight: 400;
  }

  .header-right {
    margin-left: auto;
    display: flex;
    align-items: center;
    gap: 12px;
  }

  .nav-link {
    color: var(--text-2);
    font-size: 12px;
    font-family: var(--mono);
    transition: color 0.15s;
  }

  .nav-link:hover {
    color: var(--text-0);
  }

  .nav-link.active {
    color: var(--accent);
  }

  .user-menu {
    position: relative;
  }

  .user-menu-button {
    background: transparent;
    color: var(--text-2);
    font-size: 12px;
    font-family: var(--mono);
    border: none;
    cursor: pointer;
    transition: color 0.15s;
    display: flex;
    align-items: center;
    gap: 4px;
  }

  .user-menu-button:hover,
  .user-menu-button.open {
    color: var(--text-0);
  }

  .caret {
    font-size: 8px;
  }

  .overlay {
    position: fixed;
    inset: 0;
    z-index: 99;
  }

  .dropdown {
    position: absolute;
    right: 0;
    top: 100%;
    margin-top: 6px;
    background: var(--bg-2);
    border: 1px solid var(--border);
    border-radius: var(--radius);
    padding: 4px 0;
    min-width: 120px;
    z-index: 100;
  }

  .dropdown-item {
    display: block;
    width: 100%;
    padding: 6px 12px;
    font-size: 12px;
    color: var(--text-1);
    background: transparent;
    text-align: left;
    font-family: var(--mono);
    transition: background 0.1s;
  }

  .dropdown-item:hover {
    background: var(--bg-3);
  }

  .dropdown-item.active {
    color: var(--accent);
  }

  .dropdown-item.muted {
    color: var(--text-2);
  }

  .dropdown-divider {
    border-top: 1px solid var(--border);
    margin: 4px 0;
  }

  .no-padding {
    padding: 0;
    overflow: hidden;
  }
</style>
